### ISSUE TITLE
Inline Modal Section

### ISSUE THREAD

**Issue by testdriver82** [zionbuilder/zionbuilder#105]
Hi,

I tried the new Zion Builder plugin and found that some elements from the previous Kallyas Page Builder are missing. For example, the possibility of turning a section into an inline modal. Many of the available sliders are also missing. For example the Smart Slider or the IOS Slider. Are these elements still being built in?
Thanks for your answers

## Summary

Brief explanation of the feature.

### Basic example

If the proposal involves a new or changed API, include a basic code example. Omit this section if it's not applicable.

### Motivation

Why are we doing this? What use cases does it support? What is the expected outcome?

**Comment by zauan** [comment]
Hi there,

Thank you for contacting us. The kallyas update is still in progress and all elements will be available.

This being a standalone plugin, it offers its own elements and options.

Best regards,
Stefan
