### ISSUE TITLE
Feature request: Create & manage Custom Post Types and Custom Taxonomies from within Zion Builder

### ISSUE THREAD

**Issue by Infusednl** [zionbuilder/zionbuilder#122]
## Summary

Abillity to create and manage Custom Post Types and Taxonomies from within Zion Builder.

### Motivation

If someone wants to add custom post types or custom taxonomies then you'd have to create it yourself using custom PHP code or a plugin. As far as I know no builder on the market has this feature yet.

As of now I use this plugin to create and manage my custom post types and taxonomies:
- https://nl.wordpress.org/plugins/custom-post-type-maker/

However in order to keep plugins at a minimum and really make Zion Builder more powerfull it would be great if there was a settings page where we could create and manage our custom post types and taxonomies.

**Comment by swinggraphics** [comment]
I'm sure they won't do this, and that is good. CPTs etc should be managed by a separate plugin, for multiple reasons. It's beyond the scope of a page builder, specifically because if you need to disable the page builder, you don't want to lose all your data.

**Comment by zauan** [comment]
Hi,

Indeed, such a feature is out of scope of a page builder. There are many plugins that successfully perform this task and work with Zion Page Builder.

Thank you for you suggestion, however, i will close this ticket
