### ISSUE TITLE
I want to help out with translating Zion Builder to Dutch

### ISSUE THREAD

**Issue by Infusednl** [zionbuilder/zionbuilder#131]
## Summary

I would like to help out with translating Zion Builder to Dutch. Since I am from the Netherlands, most of my clients (With a few exceptions) speak Dutch.

### Motivation

Having the interface in Dutch will really improve usabillity for people here in The Netherlands.

**Comment by raluseru** [comment]
Hi,

You can add translations for the free plugin from here:

[](https://translate.wordpress.org/projects/wp-plugins/zionbuilder/)

Thank you!
