### ISSUE TITLE
Bug: Zion Builder keeps asking if I want to take the tour

### ISSUE THREAD

**Issue by Infusednl** [zionbuilder/zionbuilder#134]
**Describe the bug**
Very often, but not always, when I want to edit a Zion page I get the pop-up asking me if I want to take a tour through the pagebuilder.
I looked through all the settings but couldn't find a way to deactivate this.

**Have you tried all the steps at https://zionbuilder.io/documentation/having-problems-using-zion-builder/?**
Yes

**Steps to reproduce**
1. Edit any page in Zion Builder and often you'll get the pop-up asking if you want to take the tour although I already followed it in the beginning.

**Expected behavior**
After taking the tour the first time, this should be deactivated, or at least an option to disable it with optionally a button somewhere so people can redo the tour if needed.

**What actually happens**
Sometimes the Builder keeps asking me if I want to take a tour.

**Environment (please complete the following information):**
- OSX 10.15.1
- Google Chrome 85.0.4183.121 - official build - 64 bits
- Zionbuilder Version 1.0.2

**Comment by raluseru** [comment]
Hi, 

Thank you for letting us know about this bug, Normally, the tour should start on empty pages. We will fix this in the next update. We shall also discuss if there would be necessary to add a disable tour option in Zion dashboard.  

Best regards, 

Raluca

**Comment by Infusednl** [comment]
Thanks for the update! :)
