### ISSUE TITLE
Price lists wont add or delete elements

### ISSUE THREAD

**Issue by pushthepixel** [zionbuilder/zionbuilder#138]
**Describe the bug**
*Write a explanatory description of the bug.*

**Have you tried all the steps at https://zionbuilder.io/documentation/having-problems-using-zion-builder/?**
*Yes/No*

**Steps to reproduce**

**Expected behavior**
*What should have happend after following the steps above.*

**What actually happens**
*Provide a concise message of what is actually happening.*

**Screenshots/Videos**
*If applicable, add screenshots/videos to help explain the problem.*

**Environment (please complete the following information):**
- OS: [e.g. Windows]
- Browser [e.g. chrome version 50, IE11]
- Zionbuilder Version [e.g. 1.0.0]

**Additional context**
*Add any other context about the problem here.*

**Comment by raluseru** [comment]
Hi, 

I am sorry to hear you are having trouble using our page builder elements. I am not sure I understand the issue you are having. Do you refer to "pricing box" element ? However, we tested the "pricing box" element, and cannot reproduce the error you are encountering on our local machines. Could you please submit a ticket to hello@hogash.com with the description of your environment so we can investigate ? Please send also the WordPress link and create a temporary password and a username for us . Thank you in advance! Raluca

**Comment by raluseru** [comment]
Hi there, 

It looks like it has been a confusion. You opened an issue on the Zion builder plugin, which is a standalone plugin and has nothing to do with Dannys Wordpress Theme. A colleague will take care of your ticket related to this theme.

Have a nice day!
