### ISSUE TITLE
Feature Request: Add 'content' option in the CSS styling tab

### ISSUE THREAD

**Issue by Infusednl** [zionbuilder/zionbuilder#140]
## Summary

Please correct me if I'm wrong but I couldn't find a 'content' option in the CSS settings.
We can add it through custom css but it would be nice if this was an integrated option.

### Basic example

I regularly use the :before and :after pseudo statements to show icons for example.
However in order for them to show up we need to specify the 'content' css property:

.example-class:before {
   display: inline-block;
   position: relative;
   width: 20px;
   height: 20px;
   background: url('img/my-icon.svg');
   content: '';   <---
}

Even empty as shown above it still works and makes sure our pseudo element is visible.
Ofcourse there are a lot more usecases but this is the main thing I use the 'content' tag for.

### Motivation

It can be used to insert text, icons or just to get pseudo elements shown on the page.

For example: I am working on a Posts element that has styling options for a readmore button.
The markup looks like this (code is simplified just for this example):

<a class="be-post__readmore-btn"> .
   <span class="be-post__readmore-btn-text">Read more</span>
</a>

When we have the 'content' css field I could easily add an icon in front of the .be-post__readmore-btn-text without having to write custom css in the advanced tab.
I hope my explanation is clear enough.

Best regards,
Christiaan

**Comment by raluseru** [comment]
Hi,

Zion builder has the content input for "before" and "after" pseudo-selectors only. When you select one of those pseudo-selectors, the builder will automatically add space inside quotation marks. But, if you want to add other text in the content, an input appears if you click the pen icon located to the right of the pseudo-selector's name.

You can check more in the gifs of this article of documentation: 

https://zionbuilder.io/documentation/css-pseudo-class-selectors/

Best regards!

**Comment by zauan** [comment]
Hi,

Please let me know if i can close this ticket.

Best regards,
Stefan

**Comment by Infusednl** [comment]
Hi Stefan,

You can close this ticket. :)

**Comment by balakumarshanmugam** [comment]
@zauan  Instead of closing this ticket, you labelled it as enhancement. Was it by mistake?

**Comment by zauan** [comment]
Thanks, i will close it
