### ISSUE TITLE
Zion Builder: Shortcodes for Saved Blocks don't work!

### ISSUE THREAD

**Issue by Infusednl** [zionbuilder/zionbuilder#142]
**Describe the bug**
When testing out Saved Blocks in Zion Builder I noticed the shortcode doesn't work. It just shows the shortcode itself. This happens in my code but also with the Zion Builder Shortcode element.

I am working on my own starter theme and noticed this when I wanted to insert my header created with Zion Builder into my header.php using: <?php echo do_shortcode('[zionbuilder id="542"]'); ?>. As said this only outputs the shortcode as text.

Afterwards I tested the shortcode with the Shortcode element inside Zion Builder but this also outputs only the shortcode name

**Have you tried all the steps at https://zionbuilder.io/documentation/having-problems-using-zion-builder/?**
Yes

**Steps to reproduce**
1. Create a section in Zion Builder.
2. Save it to the Block library.
3. Create a page.
4. Enable Zion Builder and add a shortcode element.

5.1. Fill in the shortcode for the saved block. This returns only the shortcode as text.
5.2 Use <?php echo do_shortcode(''); ?> with the shortcode in any template to output the section. This also returns only the shortcode as text.

**Expected behavior**
I expect to see my saved sections. This way I can already create the header and footer with Zion Builder by showing my header and footer sections in their respectable templates: header.php and footer.php.

**What actually happens**
The shortcode gets echo'd to the page.

**Environment (please complete the following information):**
- OSX 10.15.1
- Versie 85.0.4183.121 (Official build) (64-bits)
- Zionbuilder Version 1.0.1
- Zionbuilder PRO Version 1.0.1

**Comment by raluseru** [comment]
Hi,

Thank you for pointing this out. Currently we are working to a new release and this issue will be taken care of in the next sprint.

Thank you for understanding!

**Comment by Infusednl** [comment]
Hi Raluseru,

Can you give a time estimate as to when this update is available? I have a few projects I'm working on right now that need this fixed as soon as possible.

At the bare minimum I'd need to be able to tell my clients how long they have to wait as I need the shortcode functionality for reusing a lot of parts such as the header, footer, call-to-action sections, sections for custom post types etc.

**Comment by Infusednl** [comment]
> Hi,
> 
> Thank you for pointing this out. Currently we are working to a new release and this issue will be taken care of in the next sprint.
> 
> Thank you for understanding!

Hi Raluseru,

Can you please respond to my previous question:
– Can you give a time estimate as to when this update is available?

I understand you guys are hard at work but if a feature is not working for whatever reason then I do need to keep my clients posted about the progress and especially give them an estimate. Otherwise this will only cause misunderstanding and irrritation which may ultimately result in me losing my client.

At the moment I have various projects I have to do but if this fix takes at least two weeks for example then I have to resort to another solution or perhaps built my own temporary fix. But at least I'd be able to make choice based on the estimated timeframe.

I hope to hear from you soon,

Christiaan

**Comment by raluseru** [comment]
Hi Christiaan,

I am sorry for late response, I think it would be the best to think of an alternative solution as we have everything a little delayed with the new release. 

Thank you for understanding,

Raluca

**Comment by Infusednl** [comment]
Hi Raluca,

Thanks for the quick reply and good luck with the fixes.

Best regards,
Christiaan

**Comment by zauan** [comment]
Just wanted to let you know that this was resolved and the fix will be available on the Friday update
