### ISSUE TITLE
CSS not generated when using 0 (zero) without any suffix like 'px' for input values

### ISSUE THREAD

**Issue by Infusednl** [zionbuilder/zionbuilder#143]
**Describe the bug**
I noticed that when using a 0 (zero) for input values (so without 'px', 'rem' or any other suffix) the CSS code for it doesn't get output. However inside Zion Builder it does work, just not on the frontend as it doesn't get added to the generated CSS.

I noticed this when I used position 'absolute' to create a background overlay with a 0 for the 'top', 'right', 'bottom' and 'left' input values. Also, it doesn't matter which unit type I selected for the input. Even with the unit type set to 'custom' my value of 0 didn't get shown.

Can this please be fixed as 0 is a valid CSS unit. I tested using a 0 for different kinds of elements and CSS properties but they all don't show up in the generated CSS.

**Have you tried all the steps at https://zionbuilder.io/documentation/having-problems-using-zion-builder/?**
Yes

**Steps to reproduce**
1. Edit a page in Zion Builder
2. Use 0 for any CSS property and save the page.
3. View the page on the frontend and check to see if the value that contains a 0 is present in the inspector.
4. On my end it doesn't show up.

**Expected behavior**
I expect to be able to use a 0 as a valid input value.

**What actually happens**
Any CSS properties that accept a number won't be output to the page when using a 0.

**Environment (please complete the following information):**
- MacOS: 10.15.1
- Browser Chrome 86.0.4240.75 (Officiële build) (x86_64)
- Zionbuilder Version 1.0.1
- Zionbuilder PRO Version 1.0.1

**Comment by raluseru** [comment]
Hi,

Thank you for reporting this bug. The issue was already resolved and the fix will be included in the next release ( this week ).

I will keep this ticket open until the release is available.

Best regards,
Raluca

**Comment by zauan** [comment]
The new version is live. I will now close this ticket! If you have any more problems, please don't hesitate to contact us.
