### ISSUE TITLE
Feature Request: Abillity to change Column setting for each viewport for Zion's Gallery Element

### ISSUE THREAD

**Issue by Infusednl** [zionbuilder/zionbuilder#147]
Dear Zion Team,

Please make the column setting for the Gallery element responsive.
As you can see in the screenshot below we can only set it once:

<img width="420" alt="Schermafbeelding 2020-10-30 om 13 03 26" src="https://user-images.githubusercontent.com/6600256/97703483-fdd39400-1ab0-11eb-8b92-d2ce922bac9f.png">

This should be changeable per viewport. Now I have to write custom css to change the amount of columns.

**Comment by raluseru** [comment]
Hi,

Thank you for improving Zion Builder! We implemented this feature and it will be included in the next release ( this week ).

I will keep this ticket open until the release is available.

Best regards,
Raluca

**Comment by zauan** [comment]
The new version is live. I will now close this ticket! If you have any more problems, please don't hesitate to contact us.
