### ISSUE TITLE
Feature Request: Make Button Position option changeable per viewport

### ISSUE THREAD

**Issue by Infusednl** [zionbuilder/zionbuilder#149]
Dear Zion team,

I noticed the Button Position option is not changeable per viewport. Almost 9 out of 10 times I need to change the position for mobile. Below you can see a screenshot of the property I'm talking about:

<img width="418" alt="Schermafbeelding 2020-10-30 om 13 14 17" src="https://user-images.githubusercontent.com/6600256/97704214-43449100-1ab2-11eb-9a05-f7d890759b3a.png">

As of now we have to do quite some styling with CSS that could be easily skipped if the position option was changeable per viewport thus saving us a lot of time.

**Comment by raluseru** [comment]
Hi,

Thank you for your input. This feature request has been implemented and it will be included in the next release.

I will keep this ticket open until the release is available.

Best regards,
Raluca

**Comment by Infusednl** [comment]
Thanks for the hard work!

**Comment by zauan** [comment]
The new version is live. I will now close this ticket! If you have any more problems, please don't hesitate to contact us.
