### ISSUE TITLE
Feature Request: Add indicator that shows if element has custom class(es)

### ISSUE THREAD

**Issue by Infusednl** [zionbuilder/zionbuilder#150]
Dear Zion Team,

Can you please add an indicator that shows up when an Element has custom class(es)?

Now I have to click on the Selector area each time when I want to see if an element has custom classes.
Just a simple green dot just like the CSS properties would be enough and save a lot of extra clicks.

I made a mockup below that demonstrates this:

<img width="419" alt="Schermafbeelding 2020-10-30 om 13 18 54" src="https://user-images.githubusercontent.com/6600256/97704871-73406400-1ab3-11eb-9093-8f575bfa6298.png">

**Comment by zauan** [comment]
This will be added in the next update
