### ISSUE TITLE
Bug: Absolute Positioning of elements in Zion Builder is not the same as on the front end

### ISSUE THREAD

**Issue by Infusednl** [zionbuilder/zionbuilder#152]
Dear Zion team,

I noticed when working with absolute positioned elements that the view in Zion Builder is not correct.
My elements are all over the place inside the Builder and only appear correctly on the front end.

This makes working with Absolute positioned elements really annoying as I constantly have to switch to the front end to see where my elements are.

On a project I am working on right now I have very big headlines that are absolute positioned to the sides.
Below you can see a screenshot of the frontend where it works as intended:

<img width="1920" alt="Schermafbeelding 2020-10-30 om 16 19 53" src="https://user-images.githubusercontent.com/6600256/97723222-d807b880-1acb-11eb-8ce2-a0df1efceef7.png">

In the screenshot below you can see how it looks inside Zion Builder:

<img width="1916" alt="Schermafbeelding 2020-10-30 om 16 20 10" src="https://user-images.githubusercontent.com/6600256/97723258-e05ff380-1acb-11eb-846c-86e3a6a5819e.png">

I think it has to do with the extra markup of Zion Builder's UI elements but I'm not sure. However can this be fixed?
I often use absolute elements for styling purposes and having a correct view is really essential.

If needed I can provide login credentials to the website.

**Comment by raluseru** [comment]
Hi,

Thank you for reporting this bug. The issue was already resolved and the fix will be included in the next release ( this week ).

I will keep this ticket open until the release is available.

Best regards,
Raluca

**Comment by zauan** [comment]
Hi,

This was resolved in version 1.1.0. I will close this tichet. 

If you have any other problem, please don't hesitate to contact us again.

Best regards,
Stefan
