### ISSUE TITLE
Bug: Custom Javascript doesn't get removed in 'Custom Javascript' under 'Page Options' when saving page

### ISSUE THREAD

**Issue by Infusednl** [zionbuilder/zionbuilder#155]
When I was testing out some Javascript animations, I noticed my code doesn't get removed after I deleted it and saved the page. I also tried clicking the green dot to make sure my script was removed but with no luck. When I reload Zion Builder my code is still there.

A temporary solution I found was to add two backslashes (Like this: // ) that are used for adding comments in Javascript.
Only after doing this was my code removed and replaced by two backslashes.

**Have you tried all the steps at https://zionbuilder.io/documentation/having-problems-using-zion-builder/?**
Yes

**Steps to reproduce**
1. Edit any page with Zion Builder.
2. Go to Page Options in the left sidebar.
3. Expand the Custom Javascript section and add some code.
4. Save the page.
5. Reload the page and delete the Javascript and save again.
6. In my case the Javascript I entered was not removed, even when I removed all code by clicking the green dot.

**Expected behavior**
My custom Javascript code should be removed after I cleared it.
Also I disabled WP Fastest Cache to make sure it's not because of the cache.
I also tried clicking the 'Regenerate CSS' button in the Zion Builder settings under 'Tools'.

Quick note: Can the 'Regenerate CSS' button be renamed to 'Regenerate CSS & JS'?
I couldn't find a button that regenerates my Javascript code and found by accident that this button also regenerates my Javascript.

**Environment (please complete the following information):**
- OS: MacOS
- Browser: Google Chrome Version 86.0.4240.183 (Officiële build) (x86_64)
- Zionbuilder Version 1.0.1
- Zionbuilder Pro Version 1.0.1

**Comment by zauan** [comment]
Hi,

This is to inform you that this was resolved and will be available in the update tomorrow.

**Comment by zauan** [comment]
The new version is live. I will now close this ticket! If you have any more problems, please don't hesitate to contact us.
