### ISSUE TITLE
Bug: CSS not working correctly inside Zion Builder after changing Column ID.

### ISSUE THREAD

**Issue by Infusednl** [zionbuilder/zionbuilder#156]
While working on my new portfolio website I noticed a bug when I gave my column a custom ID AFTER I changed some CSS properties.

When I view the page on the frontend everything looks alright, but when I edit it in Zion Builder it's a big mess.

Only when I go to the styling tab and change a CSS property (Doesn't matter which one) then it looks alright again.
I also inspected the element and when the page load my column already has the correct ID, only the styling is not applied until one CSS property is changed.

**Have you tried all the steps at https://zionbuilder.io/documentation/having-problems-using-zion-builder/?**
Yes

**Steps to reproduce**
1. Add an element, in my case a Column.
2. Go to the 'Styling' tab and change some CSS properties.
3. Save and view the page.
4. Edit the page again in Zion Builder and change the ID of the element, in my case a column.
5. Save and view the page.

6. Edit the page in Zion Builder again and now the styling should be gone.
7. Edit one of the CSS properties for the elements ID in the styling tab and now all CSS should load properly.

Steps 6 and 7 have to be repeated on my end in order to see the correct styling every time I edit my page.

**Screenshots/Videos**
Here you can see my page on the frontend where it looks correctly:
<img width="640" alt="Schermafbeelding 2020-11-05 om 18 01 19" src="https://user-images.githubusercontent.com/6600256/98272190-1b14d080-1f91-11eb-83e8-90abadc638c2.png">

Here you can see my screen when I edit the page in Zion Builder:
<img width="640" alt="Schermafbeelding 2020-11-05 om 18 01 47" src="https://user-images.githubusercontent.com/6600256/98272231-2667fc00-1f91-11eb-9127-11e2f41a8168.png">

**Environment (please complete the following information):**
OS: MacOS
Browser: Google Chrome Version 86.0.4240.183 (Officiële build) (x86_64)
Zionbuilder Version 1.0.1
Zionbuilder Pro Version 1.0.1

**Comment by zauan** [comment]
Hi there,

Thank you for taking the time to report this problem. I want to inform you that this was already resolved and the fix will be available this week.

Best regards,
Stefan

**Comment by zauan** [comment]
The new version is live. I will now close this ticket! If you have any more problems, please don't hesitate to contact us.
