### ISSUE TITLE
Feature Request: Advanced Posts element like Oxygen's Easy Post

### ISSUE THREAD

**Issue by Infusednl** [zionbuilder/zionbuilder#157]
## Summary

Oxygen Builder has an Easy Posts element (https://oxygenbuilder.com/documentation/builder-elements/easy-posts/).
This element allows us to easily display posts from any custom post type. However the main benefit from Easy Posts is that we can easily retrieve and style the posts that are retrieved.

This element allows us to set the WP Query parameter and edit/change the PHP template that is being used for each post in the loop. If Zion Builder would have such an element then we would never have to use a plugin to display custom post type data since such a module would allow us to create almost everything such as a portfolio grid, retrieve news posts etc.

If Zion Builder would have such an element then it would really become a serious competitor to Oxygen Builder since we wouldn't need to write a custom plugin just to retrieve and show custom post type data.

### Basic example

Please check out Oxygen's official documentation, they also include a Youtube video: https://oxygenbuilder.com/documentation/builder-elements/easy-posts

### Motivation

Although such an element would require PHP, HTML and CSS knowledge, such an advanced module would really bring Zion Builder to the next level for serious webdesigners.

If needed I can provide an Oxygen sandbox environment so you guys can test this out. Although I already suspect you guys are working on your own implementation of a posts element I just wanted you guys to know one of the features that really makes Oxygen Builder so successfull. Because with such an advanced element I could drop Oxygen for most projects.

**Comment by swinggraphics** [comment]
A Repeater element is forthcoming, per issue #180 . If there are a couple of prebuilt repeater templates and we can make our own, that will have the same effect as Oxygen's Easy Post, without the need for a separate widget. I have my fingers crossed that Zion will implement this better than Oxygen. O's Repeater and Easy Posts are such a mess.

**Comment by zauan** [comment]
I will close this tichet as the repeater functionality was added in https://github.com/zionbuilder/zionbuilder/issues/180 

this will be available in v2.0.0
