### ISSUE TITLE
Bug: Zion Keyboard Shortcuts prohibit from typing capital letters inside the Wordpress media popup screen

### ISSUE THREAD

**Issue by Infusednl** [zionbuilder/zionbuilder#158]
**Describe the bug**
When working in the media popup screen, the screen you see when you want to upload or select an image for the image element, I noticed that the keyboard shortcuts are enabled. Because of this we can't use shift to type a capital letter if that combination is also a Zion keyboard shortcut. I had an image which had an alt-tag title that started with a capital T (TV Lochem).

A workaround is to enable caps-lock for the capital letters, however it would be much more user friendly if the keyboard shortcuts could be disabled when working inside the Wordpress media screen in Zion Builder.

**Have you tried all the steps at https://zionbuilder.io/documentation/having-problems-using-zion-builder/?**
Yes

**Steps to reproduce**
1. Edit any page with Zion Builder.
2. Add an image element.
3. Open the edit screen of the image element and upload an image.
4. Give the image an alt-tag title that starts with a capital T for using shift+T.
5. Behind the background overlay of the Wordpress media popup you should see the keyboard shortcut working thus you are forced to enable Caps-lock everytime you want to type a capital letter that is also used by Zion's keyboard shortcuts.

**Expected behavior**
Being able to type capital letters with shift.

**What actually happens**
Typing capital letters by using shift fires Zion keyboard shortcuts.

**Environment (please complete the following information):**
- macOS 10.15.1
- Google Chrome Versie 86.0.4240.198 (Officiële build) (x86_64)
- Zionbuilder Version 1.0.1
- Zionbuilder Pro Version 1.0.1

**Comment by zauan** [comment]
Hi,

Thank you for your input. This was already resolved and the fix will be included in the next release ( this week ).

I will keep this ticket open until the release is available.

Best regards,
Stefan

**Comment by Infusednl** [comment]
Great to hear! Thanks for the fast response.

**Comment by zauan** [comment]
The new version is live. I will now close this ticket! If you have any more problems, please don't hesitate to contact us.

**Comment by Infusednl** [comment]
That's awesome! I'm going to take it for a spin right away!
