### ISSUE TITLE
Feature Request: Add code block to the UI

### ISSUE THREAD

**Issue by esaygo** [zionbuilder/zionbuilder#179]
## Summary

A code block with HTML/JS, PHP, and CSS  would allow for complex customizations and integrations (like implementing CPTs and ACF, loading JS libraries, etc.)

### Basic example

See Oxygen Builder's code block: https://oxygenbuilder.com/documentation/code/php-html/

### Motivation

Complex integrations and integrations with plugins that don't support shortcodes or where shortcodes are not enough.

**Comment by Infusednl** [comment]
+1 For this!

**Comment by wpfyorg** [comment]
+1 for this too

**Comment by zauan** [comment]
Hi guys,

This was implemented and it will be available in the PRO version starting with version 1.2.0

Thank you for your feedback,
Stefan
