### ISSUE TITLE
Repeater element (like Oxygen has) that can repeat DIVs using Wordpress custom query

### ISSUE THREAD

**Issue by balakumarshanmugam** [zionbuilder/zionbuilder#180]
## Summary
New element that can repeat DIVs based on Wordpress custom query.
And it should be possible to add columns/elements within each repeated DIV.
And it should be possible to style each of those sub elements.
Styles applied to one DIV should be applied across all DIVs of the repeater.
Should support custom post type in the query too.

### Basic example

1. Blog archive - To display list of blog articles, one DIV for each article, and sub elements within DIV like blog title, blog excerpt, blog thumbnail etc.
2. Display a list of professors under an University, with their name, pic, specialties etc.

### Motivation

Easy to display any list of post type and style them easily in the builder itself without writing php code and custom css.
To make use of Zion elements and styling options is much easier than custom coding.

**Comment by zauan** [comment]
HI,

This is already on our to-do list. Depending on how the site builder functionality works out, this feature will be available at the site builder update launch or shortly after this. Funny thing is that we have actually created a draft for this feature before Oxygen even implemented this.

I will update this ticket as soon as I have more information about this.

**Comment by balakumarshanmugam** [comment]
@zauan Thanks for the update. Wow, so you must have drafted this before Sep 2019!

**Comment by zauan** [comment]
Yes, it was drafted in february if i am not mistaking. But this is not the point, doesn't matter who thinks of a new feature as long as the end user gets to use it and it simplifies the workload

**Comment by zauan** [comment]
This will be available in the v2.0.0 update.

The system will work like this:
* All elements will have two main options in the advanced tab ( Repeater provider and repeater consumer )
* The repeater provider will provide the necessary query to all child/nested child consumers
* An element can be a provider and consumer at the same time ( in case you want to just repeat an element )

With this system, you can nest many consumers under a provider and for each consumer set a loop start and end index. This allows for complex designs to be created
