### ISSUE TITLE
Options panel not showing correct data when switching between elements/columns/sections

### ISSUE THREAD

**Issue by balakumarshanmugam** [zionbuilder/zionbuilder#181]
**Describe the bug**
When the options panel remains open... If I edit one element, and go to styling tab, style the wrapper or a class, it is fine. Now if I edit another element, the options panel shows the previous element's id or class as selected. Rather it should be dynamically pick the id/default class of the item that's currently selected for editing.

**Have you tried all the steps at https://zionbuilder.io/documentation/having-problems-using-zion-builder/?**
No

**Steps to reproduce**
1. Add few sections/columns/elements to a page.
2. Edit an element, add a class, style the element using the class.
3. Now edit another element by keeping the options panel open.
4. The options panel still shows the class that was applied to the previous element. I have to manually choose wrapper to change the id/class I want to use for styling.

This is a bug. Since the class of previous element is not applied to the current element that's being edited, but it still shows the class.

**Expected behavior**
Options panel should show the data for the newly selected element/column/section for editing.

**What actually happens**
It shows the id/class of the previously edited item.

**Environment (please complete the following information):**
Windows
Chrome Version 86.0.4240.198 (Official Build) (64-bit)
Zionbuilder Version 1.0.0

**Comment by zauan** [comment]
Just wanted to let you know that this was resolved and the fix will be available on the Friday update
