### ISSUE TITLE
Styling tab extra click

### ISSUE THREAD

**Issue by balakumarshanmugam** [zionbuilder/zionbuilder#185]
## Summary

Now when I click on the styling tab on the Options panel, it shows "Wrapper". It doesn't add any value to me.

![image](https://user-images.githubusercontent.com/25269667/100520120-76a33a00-319c-11eb-8565-93abc07e3ad5.png)

I have to click that "Wrapper" link then go to the actual styling applied to the wrapper, like below.

![image](https://user-images.githubusercontent.com/25269667/100520143-99355300-319c-11eb-8cad-418bb21f4388.png)

Rather I'd like to go directly to the styling applied to the wrapper when I click on the styling tab. That extra click adds a lot of delay especially while styling a lot of elements. Or maybe I'm missing something, and it's there for a reason?

### Motivation

Faster styling

**Comment by zauan** [comment]
Hi,

Unlike other builders, some of our elements allows you to fully style inner elements.  For example, if you look at the section, you can style both the section wrapper and the inner wrapper.  I understand that most of the elements only generate one HTML element and for this there is only one level of styling ( wrapper ) however, if we change the behavior and automatically open the wrapper style page for elements that only have one level of styling would introduce two behaviors that apply when clicking on the styling tab  based on the number of inner elements.

If it's ok with you, i would like to close this ticket. If not, i am open to further discuss this.

**Comment by balakumarshanmugam** [comment]
Hi Stefan,

Thanks for the explanation. Just checked the styling of a section. It makes sense.
Yes, you're right by saying that if you allow opening directly to wrapper style for elements that only have wrapper and no inner content, there will be two behaviour. But wouldn't that make styling easier and save time.

Or maybe introduce two new options in the edit tab 
1. Style wrapper
2. Style inner content

Also please add shortcuts for each edit icon, because I find it time-consuming while clicking the edit icon and selecting an action. Having a shortcut to style directly the wrapper and inner content will be more user friendly.

Thanks for discussing this further.

**Comment by balakumarshanmugam** [comment]
@zauan yes, you are right. Because I just checked the count down timer element. And there are 3 wrappers. So it will be confusing if you allow directly opening the wrapper for one type of element, and showing the wrappers for other types. So, it's good as it is now.

Please close this incident.
