### ISSUE TITLE
Shift + L doesn't close the library panel

### ISSUE THREAD

**Issue by balakumarshanmugam** [zionbuilder/zionbuilder#187]
**Describe the bug**
Pressing Shift + L opens the Library panel. But since the focus is on the search text box, pressing Shift + L doesn't close the panel. Rather it types L in caps in the text box. So, the toggling doesn't work. Instead of Shift + L, you may assign the shortcut key "Esc" to close the Library panel.

**Have you tried all the steps at https://zionbuilder.io/documentation/having-problems-using-zion-builder/?**
Yes

**Steps to reproduce**
1. Edit any page using Zion
2. Press Shift + L. It will open Library panel
3. Press Shift + L again. It won't close the panel. Rather it will type in the search textbox.

**Expected behavior**
Library panel should get closed

**What actually happens**
Types in the search text box.

**Comment by zauan** [comment]
Hi,

We have implemented the escape key option. Now, when you press the escape key while the library modal is open, the modal will close.

This will be available in the 1.2.0 update
