### ISSUE TITLE
Feature Request: Add a DIV elemenet

### ISSUE THREAD

**Issue by balakumarshanmugam** [zionbuilder/zionbuilder#189]
## Summary

Now the only way to add only one DIV element is by adding a single-cell column. But in the markup, it will add two DIVs in the markup. There are cases where it is just needed to wrap something in DIV, and it would be useful to have a DIV element.

### Motivation

To reduce the number of DOM elements for simpler scenarios where only one DIV wrapper is needed.

**Comment by zauan** [comment]
Hi there,

There is no need to add a new element as the column only adds 1 div element. Please note that in editor mode, additional div elements are needed, however, in rendered page it will output only 1 div.

![image](https://user-images.githubusercontent.com/5928748/100580323-63a07f00-32ee-11eb-8414-639cf9484b94.png)

As you can see in the image, I have 1 column with 1 text element. Each generating 1 div.

Please let me know if you have additional info regarding this or I can close this ticket.

best regards,
Stefan

**Comment by balakumarshanmugam** [comment]
Sorry, I overlooked. This looks good. So, closing this incident.
