### ISSUE TITLE
Bug with Icon element

### ISSUE THREAD

**Issue by balakumarshanmugam** [zionbuilder/zionbuilder#191]
**Describe the bug**
Icon size, spacing and other styling are not possible from the General tab -> Icon styles.
Also, the design of this element differs from others. For other elements, every wrapper, element styles are kept in the styling tab. But for this, it is available in the General tab. The controls in the Icon styles under general tab don't work.

**Have you tried all the steps at https://zionbuilder.io/documentation/having-problems-using-zion-builder/?**
Yes

**Steps to reproduce**
1. Add a new icon element.
2. Go to General tab -> Icon styles.
3. Adjust Icon size, space around icon, Icon rotate.
4. No styling will be applied to the icon element both in the builder and in the front end.

**Expected behavior**
Styling should be applied in the builder and in the front end.

**What actually happens**
No styling is applied to the icon.

**Screenshots/Videos**

![image](https://user-images.githubusercontent.com/25269667/100582929-4964a200-32ea-11eb-8fa2-62351832bacf.png)

**Environment (please complete the following information):**
- OS: Windows
- Browser Chrome/Firefox Developer
- Zionbuilder Version: 1.1.0

**Comment by zauan** [comment]
Just wanted to let you know that this was resolved and the fix will be available on the Friday update
