### ISSUE TITLE
Bug: Accordion element doesn't work

### ISSUE THREAD

**Issue by balakumarshanmugam** [zionbuilder/zionbuilder#192]
**Describe the bug**
If I add an accordion element to a page, this works in the builder. I can expand and collapse. But if I see the page in the front-end, I'm not able to expand or collapse. When I click the header, nothing happens.

**Have you tried all the steps at https://zionbuilder.io/documentation/having-problems-using-zion-builder/?**
Yes

**Steps to reproduce**
1. Add an accordion element to a page
2. See the page in front-end. Click on one of the accordion headers.
3. The accordion panel doesn't open.

**Expected behavior**
Accordion panel opens/collapses when clicking on its header

**What actually happens**
Nothing happens on clicking the accordion header

**Environment (please complete the following information):**
- OS: Windows
- Browser: Chrome/Firefox Developer
- Zionbuilder Version: 1.1.0

**Comment by zauan** [comment]
Hi,

thank you for submitting this ticket, I've just tested and I can confirm it is a bug. It will be resolved shortly

**Comment by zauan** [comment]
Just wanted to let you know that this was resolved and the fix will be available on the Friday update
