### ISSUE TITLE
Add element button (Blue + button) isn't available under columns

### ISSUE THREAD

**Issue by balakumarshanmugam** [zionbuilder/zionbuilder#195]
## Summary

I don't see a blue colored + button inside a column. And hence I'm not able to add a new element within a column. The workaround is to add an element outside of the column and then drag it inside the column. If I have one element within the column, then I get the blue + button using which I can add new elements within the same column. But in the tree view, the blue + icon doesn't appear even if there is one element. Two bugs to be fixed

1. Blue + button not visible inside a column when there is no element.
2. Blue + button not visible at all inside a column in the tree view in all scenarios

![image](https://user-images.githubusercontent.com/25269667/100585935-ab270b00-32ee-11eb-9888-9d4854d7fb30.png)

### Motivation

Add elements within a column easily

**Comment by zauan** [comment]
Hi,

I have just tested this and I see the icons to add new elements inside the column ( the yellow plus ). Can you confirm that this can be used to add elements inside the columns?

As a note, the add icons are currently styled based on the element ( blue for sections/yellow for columns and elements ). I believe it doesn't add a real benefit for the end-user and I propose a different color scheme based on where the plus button actually adds the element:
- Blue adds a new element inside the current element( inside columns/sections )
- Yellow adds new elements after the current element

**Comment by balakumarshanmugam** [comment]
@zauan yes, you are right. I'm able to add elements within a column using the yello +. I was thinking blue + is the one to be used to add elements inside a section or a column because when I add the first element within a column, I get to see blue + next to the first element to add further elements. See below. So, yes, like you said, it's confusing. 

And your suggestion for color scheme will work better.
![image](https://user-images.githubusercontent.com/25269667/100588714-7917a800-32f2-11eb-8ea8-28b0854c1571.png)

I'm closing this incident.
