### ISSUE TITLE
Automatically refresh the page after inserting the API key

### ISSUE THREAD

**Issue by zauan** [zionbuilder/zionbuilder#196]
At the moment, there is no feedback after inserting the API key and the user has to manually refresh the page in order to have access to PRO features. We need to automatically refresh the page by adding window.location.reload() after the API key was successfully added

**Comment by raluseru** [comment]
Issue solved on Zion Builder Pro plugin

**Comment by zauan** [comment]
Just wanted to let you know that this was resolved and the fix will be available on the Friday update
