### ISSUE TITLE
Zion builder doesn't work on some elements

### ISSUE THREAD

**Issue by PennyLava** [zionbuilder/zionbuilder#200]
Hello, I'm trying to use Stepbox 2 using Zion page builder. Unfortunately, when I click on the button "add more" nothing happens. The same happens when I try to add some social icons on "Big Social Box" and "Social Icons List"

Can you please help me?

Thank you

**Comment by balakumarshanmugam** [comment]
Many elements are buggy right now. All elements need a relook. Maybe after migrating to Vue 3, many of them broke?

**Comment by zauan** [comment]
@PennyLava Thanks for opening a new ticket. I believe you are using the version that shipped with Kallyas or a different theme. If so, please contact the theme developer for support as the Element in question is not provided natively by Zion Builder.

@balakumarshanmugam Indeed, after migrating to Vue 3 small issues appeared for some elements. A new update will be released this week to fix all reported problems.
