### ISSUE TITLE
Saved Zion section used in Shortcode not displaying correctly inside the builder

### ISSUE THREAD

**Issue by Infusednl** [zionbuilder/zionbuilder#224]
**Describe the bug**
I just updated to the newest Zion Builder free (1.2.0) and Pro (1.2.0).
However I noticed that sections which are saved to the block library don't show up correctly inside the builder.
On the frontend it does show up correct.

I attached two screenshots where you can see this.

**Have you tried all the steps at https://zionbuilder.io/documentation/having-problems-using-zion-builder/?**
*Yes/No*

**Steps to reproduce**
1. Create a section and save it.
2. Add a shortcode element on any page and paste in the shortcode of the created section.
3. Inside Zion Builder it looks like its broken but on the frontend it does load correctly.

**Expected behavior**
That saved blocks show the right appearance. Not it looks like its broken in Zion Builder.

**What actually happens**
It looks like it can't get it styles for some reason.

**Screenshots/Videos**
How it looks inside Zion Builder(Broken):
<img width="1440" alt="Schermafbeelding 2020-12-07 om 17 40 00" src="https://user-images.githubusercontent.com/6600256/101379083-2a4ead00-38b4-11eb-8860-6c7293fbe547.png">

How it looks on the front end(Correct):
<img width="1440" alt="Schermafbeelding 2020-12-07 om 17 40 09" src="https://user-images.githubusercontent.com/6600256/101379156-405c6d80-38b4-11eb-81ba-57df6acd4e01.png">

**Environment (please complete the following information):**
- MacOS Big Sur version 11.0.1
- Chrome version 86.0.4240.198 (Officiële build) (x86_64)
- Zionbuilder Free 1.2.0
- Zion Builder Pro 1.2.0

**Comment by zauan** [comment]
This has been resolved in the v2.0.0 update on 02.03.2021
