### ISSUE TITLE
Classes don't work in some cases

### ISSUE THREAD

**Issue by balakumarshanmugam** [zionbuilder/zionbuilder#227]
**Describe the bug**
Styling an element using a class doesn't work in some cases. We'll have to use the ID to style it; only then it works.
This is a bug in many elements.

**Have you tried all the steps at https://zionbuilder.io/documentation/having-problems-using-zion-builder/?**
Yes

**Steps to reproduce**
Let me use the Tabs element for an example.
Let me first show where class works.
1. Add a tab element.
2. Style the wrapper.
3. Add a class to the wrapper, say for example "wrap-tab".
4. Set backgroun color for the wrapper, keeping the above class as active.
5. This one works, and changes the background of the wrapper.
![image](https://user-images.githubusercontent.com/25269667/101388142-d5b12f00-38bf-11eb-8dd2-95cf1c9594b2.png)

Let me show an example where the class doesn't work
1. Now, in the styling tab, select "Tab styles"
2. Add a new class, say for example, "tab-element".
3. Set the background color while keeping this class active.
4. The background color I set is not applied to the tabs.
See screenshot below
![image](https://user-images.githubusercontent.com/25269667/101388466-47897880-38c0-11eb-8564-d9b2630140e7.png)

The class "tab-element" is not actually added to the <li> element. That's the issue. See screenshot below.
![image](https://user-images.githubusercontent.com/25269667/101388731-a7801f00-38c0-11eb-9b90-e44fdee7dcfb.png)

If I add the class "tab-element" to the <li> element, then the color applies. See screenshot below.
![image](https://user-images.githubusercontent.com/25269667/101388889-d8f8ea80-38c0-11eb-9f22-6bf978cd45e8.png)

This is the case with most styling tabs of most elements. The class that we add in Zion builder doesn't get added to the DOM.

This is issue number 1. The next issue is that, in some cases, even if I add the class manually to the DOM, the styles won't apply because there are more specific selectors in the OOB Zion builder css.
An example for the above case.
1. In the same tabs element, open "Active tab styles" in the styling tab.
2. Add a new class named "active-tab-element".
3. Set background color keeping this class active and on ":after" pseudo element (which is the bottom border of the active tab).
4. This background color won't be applied to the active tab bottom border.
5. In the DOM, I can manually add the class "active-tab-element" to see if adding the class works or not.
6. The issue is that the color doesn't change even after adding the class, because there are more specific selectors in the Zion builder CSS. The only way for me to change the bottom border of an active class is to style "ID :after".
See screenshot below.
![image](https://user-images.githubusercontent.com/25269667/101389615-fc706500-38c1-11eb-8d28-33f0dac29b41.png)

**Environment (please complete the following information):**
- OS: Windows
- Browser: Chrome
- Zionbuilder Version: 1.2.0

**Comment by zauan** [comment]
Hi,

Thank you for reporting this issue. A quick fix will be released tomorrow.

Best regards,
Stefan

**Comment by balakumarshanmugam** [comment]
> Hi,
> 
> Thank you for reporting this issue. A quick fix will be released tomorrow.
> 
> Best regards,
> Stefan

@zauan Thanks. Hope the fix is also for the 2nd point I mentioned.
i.e. currently, if you add class to any element, it is not overriding Zion's default CSS. So, the only way to override Zion's is by styling the ID. Since currently, while adding classes to elements, the CSS is not more specific and hence it's not overriding the Zion's class, which is way more specific with lots of classes in the selector.

**Comment by zauan** [comment]
Hi,

Just a heads up that the first issue will be resolved today.

The second one requires more testing and we cannot release a quick fix for it today. I will open a separate ticket containing just the second problem.

**Comment by balakumarshanmugam** [comment]
> Hi,
> 
> Just a heads up that the first issue will be resolved today.

@zauan I tested the fix for the first one. This is not completely fixed. In the builder, the class is applied, but in the front-end, the class is not added to the element, and hence no change in the styles. Please see below the screenshots of builder and front-end.

Builder:
![image](https://user-images.githubusercontent.com/25269667/101521234-d6ac9400-3985-11eb-8381-c378ecacc2b4.png)

Front-end:
![image](https://user-images.githubusercontent.com/25269667/101521264-e330ec80-3985-11eb-81cb-b591f5f303b2.png)

**Comment by balakumarshanmugam** [comment]
@zauan Since now we aren't able to override default Zion styles using custom classes, the only way to style elements is by using their ID. This is very inconvenient. Please see below, the styles I added to a class are not respected since Zion's classes are more specific. Only the background color from my class is applied since the background color is not set in Zion's default class. If this is not fixed, then the whole class system will be of waste. Please fix this

![image](https://user-images.githubusercontent.com/25269667/101524135-d7472980-3989-11eb-8efc-8361e9af0935.png)

**Comment by zauan** [comment]
This has been resolved in v2.0.0 that will be released on 02.03.2020
