### ISSUE TITLE
Icon element styling opens "Hover" by default which is confusing

### ISSUE THREAD

**Issue by balakumarshanmugam** [zionbuilder/zionbuilder#228]
**Describe the bug**
While trying to style an icon, "Hover" option opens by default. And normally users tend to style "Hover" and not see if reflect in the builder and on the front end. This is very confusing. "Normal" tab should open by default instead of "Hover"

**Have you tried all the steps at https://zionbuilder.io/documentation/having-problems-using-zion-builder/?**
Yes

**Steps to reproduce**
1. Add an icon element.
2. Open icon options -> General tab
3. Click Icon styles
4. This opens the icon styles, and "Hover" tab is active by default.
5. I tend to style the "Hover" of the icon and I don't see the styling reflect in the builder. It is very confusing.

**Expected behavior**
"Normal" tab should open by default in the icon styles

**What actually happens**
"Hover" tab opens by default

**Environment (please complete the following information):**
- OS: Windows
- Browser Chrome
- Zionbuilder Version: 1.2.0

**Comment by zauan** [comment]
Closing as resolved in v1.2.1
