### ISSUE TITLE
Avoid extra click while changing an icon in the icon element

### ISSUE THREAD

**Issue by balakumarshanmugam** [zionbuilder/zionbuilder#229]
## Summary

When changing the icon in an icon element, I have to click insert to make the changes.
Normal user behavior would be to select the new icon and then close the selection window. But if I do that, the newly-selected icon won't apply. The "insert" button doesn't add any value here. Rather it's an additional click for changing an icon.

### Motivation

To avoid confusion while changing icon and reduce an extra click.

![image](https://user-images.githubusercontent.com/25269667/101408391-a2c96400-38dc-11eb-92fe-4954e968d069.png)

**Comment by raluseru** [comment]
Hi, I will close this ticket as the issue has been implemented in the latest release. 

Best regards,

Raluca
