### ISSUE TITLE
Column styling options not showing on Safari on MacOS Big Sur 

### ISSUE THREAD

**Issue by Infusednl** [zionbuilder/zionbuilder#234]
**Describe the bug**
The styling options for the column element are not showing on Safari on my 15" macbook (late 2015) running MacOS Big Sur 11.0.1. I also checked my console but it didn't show any JS errors.

I noticed this problem does not appear in Google Chrome on MacOS Big Sur.

**Have you tried all the steps at https://zionbuilder.io/documentation/having-problems-using-zion-builder/?**
Yes

**Steps to reproduce**
1. Edit any column element in Zion Builder on a Mac.
2. Go to the styling tab.
3. Click on Wrapper
4. The styling options for the wrapper are gone. Sometimes they are visible for like 0.2 seconds before they disappear.

**Expected behavior**
I expect to see the styling options.

**What actually happens**
The styling options for columns are gone when editing in Safari on MacOS Big Sur.

**Screenshots/Videos**
NOTE: Although it says Form Wrapper Options it's just a regular column which I renamed.
<img width="780" alt="Schermafbeelding 2020-12-08 om 12 52 29" src="https://user-images.githubusercontent.com/6600256/101484265-a51dd380-3959-11eb-987d-20650afa41e5.png">

**Environment (please complete the following information):**
- MacOS Big Sur 11.0.1
- Safari 14.0.1
- Zionbuilder Free & Pro Version 1.2.0

**Additional context**
I tested this in Google Chrome and Safari but the problem only persists in Safari.

**Comment by zauan** [comment]
hi,

indeed, this seems to be a problem affecting Safari. A fix will be available later today. At the moment, there is no workaround except using a different browser.

**Comment by Infusednl** [comment]
Thanks for the quick response! As mentioned in the ticket it works perfectly fine in Chrome so I'm all good for now. :)

**Comment by zauan** [comment]
Closing as resolved in v1.2.1
