### ISSUE TITLE
Page Builder moved

### ISSUE THREAD

**Issue by aheil123** [zionbuilder/zionbuilder#249]
**Describe the bug**
Hi - I was working in the page builder and closed out of it. When I went back just minutes later, the entire bottom panel shifted to the right and I cannot get to the elements. See image 

**Have you tried all the steps at https://zionbuilder.io/documentation/having-problems-using-zion-builder/?**
*No - nothing in there about the issue*

**Steps to reproduce**
1. Go to 'a page created in wordpress'
2. Click on 'edit with Zion builder'
3. See error

**Expected behavior**
*The should display full screen.*

**What actually happens**
*The left side of the panel displays mid-way through the page and cuts off the right side*

**Screenshots/Videos**
*If applicable, add screenshots/videos to help explain the problem.
![image](https://user-images.githubusercontent.com/75755373/101681149-58083300-3a27-11eb-9bbb-20a5ff9c4bf6.png)
*

**Environment (please complete the following information):**
- OS: Windows
- Browser chrome Version 87.0.4280.88
- Zionbuilder Version 1.2.2

**Additional context**
*I did update to Wordpress 5.6*

**Comment by aheil123** [comment]
I have some additional info. I Insteaped the page and found these errors:

DevTools failed to load SourceMap: Could not load content for http://jamcop4.dreamhosters.com/wp-content/themes/kallyas/framework/zion-builder/assets/css/css-source-maps/znb_frontend.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

DevTools failed to load SourceMap: Could not load content for http://jamcop4.dreamhosters.com/wp-content/themes/kallyas/framework/zion-builder/assets/css/css-source-maps/zn_front_pb.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

DevTools failed to load SourceMap: Could not load content for http://jamcop4.dreamhosters.com/wp-content/themes/kallyas/css/css-source-maps/template.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by aheil123** [comment]
I have some additional info. I Inspected the page and found these errors:

DevTools failed to load SourceMap: Could not load content for http://jamcop4.dreamhosters.com/wp-content/themes/kallyas/framework/zion-builder/assets/css/css-source-maps/znb_frontend.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

DevTools failed to load SourceMap: Could not load content for http://jamcop4.dreamhosters.com/wp-content/themes/kallyas/framework/zion-builder/assets/css/css-source-maps/zn_front_pb.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

DevTools failed to load SourceMap: Could not load content for http://jamcop4.dreamhosters.com/wp-content/themes/kallyas/css/css-source-maps/template.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by raluseru** [comment]
Hi,

This is not the place for issues of products used in Kallyas theme. For opening a ticket related to the page builder included in Kallyas, please go to the dedicated platform[ my.hogash.com](url) .

Best regards,

Raluca
