### ISSUE TITLE
Register on Packagist

### ISSUE THREAD

**Issue by szepeviktor** [zionbuilder/zionbuilder#28]
Please register on Packagist

https://packagist.org/packages/hogash/zionbuilder

```bash
composer require hogash/zionbuilder
```

To be used in [Composer-based WordPress installations](https://github.com/szepeviktor/wordpress-install/blob/master/composer.json).

**Comment by zauan** [comment]
@all-contributors please add @szepeviktor  for ideas

**Comment by zauan** [comment]
@all-contributors please add @szepeviktor for ideas

**Comment by zauan** [comment]
@all-contributors please add @szepeviktor for ideas

**Comment by szepeviktor** [comment]
@zauan Any progress on this?

**Comment by zauan** [comment]
Added on packagist. From what I see, plugins can also be installed using https://wpackagist.org/

**Comment by szepeviktor** [comment]
> From what I see, plugins can also be installed using [wpackagist.org](https://wpackagist.org/)

Yes, that is like scratching you left ear with your right hand.

- wpackagist work like: user's composer command -> wpackagist -> wp.org
- `zionbuilder/zionbuilder` is simply: user's composer command -> packagist
