### ISSUE TITLE
Change Icon Color - Free Version

### ISSUE THREAD

**Issue by herschel-w** [zionbuilder/zionbuilder#286]
Hi,
Thanks for a very good plugin. I just wanted to know if one
can change the icon colors in the free version? 
If yes, I cannot see where to do it.
I would like to change to green and red.

https://tests.quizerks.com/icon-color.png
Thanks a lot

**Comment by raluseru** [comment]
Hi,

Thank you for opening a ticket with this issue. Currently, you can change the color of the icon if you go to Styling tab > Icon Styles > Typography > Font Color.  I attached some screenshots.
[step1](https://monosnap.com/direct/GAYBwXk36X0iJxQmuBUI0EMV5L4aAH)
[step2](https://monosnap.com/direct/3ATgDuoMtXaJLPM1SKlR1cDsIqkbdo)

If it is more user friendly, we could also add in general tab a shortcut for the icon color.

Best Regards.
Raluca

**Comment by herschel-w** [comment]
Thanks a mill Raluca, I will try it out.
