### ISSUE TITLE
Header & Footer Builder - Coming soon!

### ISSUE THREAD

**Issue by ubrax** [zionbuilder/zionbuilder#306]
Bought the pro builder for the header functionality (Infocard as in Kallyas).

You indicated on the salers page that: "Header & Footer Builder - Coming soon!"

Avada launched Avada Builder in Avada 7.2.1 with their new header builder already.

When can I expect the pro version of Zion Builder to contain a functioning Header / Footer builder?

I'll appreciate your urgent completion and incorporation of Kallyas Header Functionality in Zion Builder (Header/Footer) Builder, please!

Regards, and thank you

Hendrik Pretorius (ZION USER: PRAETORIUM)

**Comment by ubrax** [comment]
Can someone please tell me when this feature (Header & Footer Builder) will be available? No support here?

**Comment by raluseru** [comment]
Hi Hendrik,

The theme builder is currently in beta testing. If you want, we can give you the zip archives with the new versions of the plugins to test it. 

Best regards, 
Raluca

**Comment by HansChristianto** [comment]
Hi Raluca, 

Yes, please. Can you give that too?

Thank you

Best Regards,
Hans Christianto

**Comment by ubrax** [comment]
Dear Raluca

I'll appreciate a beta release for internal testing.

Thank you

Regards

Hendrik Pretorius

Quoting Lalú Selú <notifications@github.com>:

>  
>
>   Hi Hendrik,
>
>   The theme builder is currently in beta testing. If you want, we  
> can give you the zip archives with the new versions of the plugins  
> to test it.
>
>   Best regards,
> Raluca
>
>   —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub[1], or unsubscribe[2].
> [ { "@context": "http://schema.org", "@type": "EmailMessage",  
> "potentialAction": { "@type": "ViewAction", "target":  
> "https://github.com/zionbuilder/zionbuilder/issues/306#issuecomment-766672182", "url": "https://github.com/zionbuilder/zionbuilder/issues/306#issuecomment-766672182", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } }  
> ]



Links:
------
[1]  
https://github.com/zionbuilder/zionbuilder/issues/306#issuecomment-766672182
[2]

**Comment by raluseru** [comment]
Hi Hendrik,

Thank you for your interest in the Beta version. On Monday you will find the zip archive in the zionbuilder.io account. 

Best Regards, 
Raluca

**Comment by ubrax** [comment]
Thx Raluca, I appreciate it!
Have a wonderfull weekend. 
Regards, and thank you.
Hendrik

**Comment by ubrax** [comment]
Hi Raluca

Now Thuesday 2 Jan. Still no zip archive in my zionbuilder.io account.  
Will it be available under "Downloads" in my profile?

Regards, and thank you

Hendrik Pretorius

Quoting Lalú Selú <notifications@github.com>:

**Comment by raluseru** [comment]
Hi Hendrik, 

Can you please check now?

Best regards!

**Comment by zauan** [comment]
This was added in version 2.0.0
