### ISSUE TITLE
Can't add buttons

### ISSUE THREAD

**Issue by narthexius** [zionbuilder/zionbuilder#348]
Hey there,

On propertyone.com, I'm trying to edit the footer, which is a smart area I think, and whenever I hit "Edit with zion builder" and scroll down, it won't let me use the "Add more" feature on the "buttons group" element. Any help would be greatly appreciated. I can't clone or edit the buttons either. Thanks

**Comment by raluseru** [comment]
Hi there, 

Smart areas are form Kallyas theme. Please open a ticket on my.hogash.com 
Github issues are for the standalone plugin.

Thank you for understanding!
