### ISSUE TITLE
Feature Request: Adding WP classes to <body> for Theme Builder templates

### ISSUE THREAD

**Issue by Infusednl** [zionbuilder/zionbuilder#349]
Dear support,

After testing out the beta version of the Theme Builder I noticed that the <body> doesn't contain any classes.
Wordpress has the body_class() function (https://developer.wordpress.org/reference/functions/body_class/) that automatically inserts various classes.

On my own website I have a custom post type called Quotes. I created a vertical Header layout for this post type using the Theme Builder. This vertical header is fixed to the left and has a width of 220px.

However this header overlaps the page content. To resolve this I could add a padding-left of 220px to the body so the content is fully visible. If the body for each Theme Builder Layout has a custom class I could do something like this:

body.zb-layout-quotes {
  padding-left: 220px;
}

## Summary

Please add a custom class in the <body> element for each Theme Builder layout. This makes advanced styling possible. Such as a vertical header that doesn't overlap page content.

### Motivation

Allow more creative freedom for advanced layouts.

**Comment by zauan** [comment]
Hi,

thank you for opening this ticket. I want to inform you that this was resolved and it will be included in the next plugin update.

Best regards,
Stefan
