### ISSUE TITLE
Feature Request: Inner Content element for Body layout in Theme Builder

### ISSUE THREAD

**Issue by Infusednl** [zionbuilder/zionbuilder#352]
Dear support,

In Oxygen we have an Inner Content (https://oxygenbuilder.com/documentation/templating/templating-overview/) element that we can use inside a template.
This Inner Content element is used to display the contents of a post.

It would be awesome if this would be available in the Body layout inside the Theme Builder.

This would allow us to add, for example, global elements to a Body layout. This way we don't have to put those elements manually inside each post. These could be elements that are global but wouldn't be logical to put inside the Header layout.

As of now when we create a Body layout it replaces the post content. By having an Inner Content element we can bypass this.

## Summary

Having the abillity to add elements to the Body layout without replacing the content of a post.

### Motivation

This would allow for more complex and advanced layouts.

**Comment by zauan** [comment]
This will be added in the next update
