### ISSUE TITLE
Feature Request: Add object-fit & object-position to CSS properties panel

### ISSUE THREAD

**Issue by Infusednl** [zionbuilder/zionbuilder#365]
Dear support,

I'd like to request the CSS property 'object-fit' to be added to the CSS properties panel.
This way we have more control over how images and videos are placed and positioned.
It's one of the most handy properties available that allow for truly creative control.

## Summary

An excerpt taken from CSS Tricks (https://css-tricks.com/almanac/properties/o/object-fit/):

The object-fit property defines how an element responds to the height and width of its content box. It’s intended for images, videos and other embeddable media formats in conjunction with the object-position property. Used by itself, object-fit lets us crop an inline image by giving us fine-grained control over how it squishes and stretches inside its box.

### Basic example

You can view the documentation on object-fit here:

- https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit

### Motivation

Allow for more creative control over images and videos.

**Comment by zauan** [comment]
This will be added in the next update
