### ISSUE TITLE
Feature Request: Shape Dividers - Mask Height is NOT responsive

### ISSUE THREAD

**Issue by Infusednl** [zionbuilder/zionbuilder#369]
Dear support,

I noticed that the Mask Height property for Shape Dividers is not responsive.
Please make this responsive so we can effectively control how Shape Dividers look on all devices.

Example, on Desktop I need a Mask Height of 300px. However on tablet and mobile this is way to high thus I need a lower value. But when I changed this on tablet and mobile I noticed that the height also changed on Desktop. In other words, we can only set one height for all devices.

## Summary

Being able to set different heights for Shape Dividers across all devices.

### Motivation

Being able to style Shape Dividers correctly to fit on all devices nicely.

**Comment by zauan** [comment]
Resolved in https://github.com/zionbuilder/zionbuilder/pull/389
