### ISSUE TITLE
Feature Request: Integration with Blocksy theme

### ISSUE THREAD

**Issue by Infusednl** [zionbuilder/zionbuilder#378]
Dear support,

Is it possible to get you guys in contact with the people from Blocksy?

A lot of people, including those in the Zion Builder FB group recommended the Blocksy theme after I made a post about WP Astra. After purchasing Blocksy Pro and doing some extensive tests, I immediately fell with the theme as it is way more versatile than Astra and the perfect companion to Zion Builder.

The only thing that doesn't work yet is Content Blocks (https://creativethemes.com/blocksy/docs/premium/content-blocks/). These allow us to create layouts with Zion Builder that can be inserted on the website through various hooks with lots of conditional rules.

However, just like Astra's Custom Layouts module it does seem to require a special integration before Zion Builder is fully compatible. When I edit a Content Block with Zion Builder everything loads normally, except the content that I build with Zion Builder is not visible on the page I am working on, this happens inside the builder and on the frontend.

I already contacted Blocksy support and they commented the following:

— — —

Hi Christiaan,

I've spoken with the development team and will try to prioritise this and get out an update asap. Keep an eye out 👀

Thank you for your patience and support,
Eduard

— — —

Perhaps they can manage everything themselves but I still wanted to write this ticket just in case someone else also uses Blocksy Pro or wants to use it. This way they know the current state of integration. Anyway, I myself like the theme so much that I've decided to replace Astra with the Blocksy theme.

## Summary

Full integration with Blocksy Pro theme. Zion Builder already works on pages, it just doesn't work when building a layout with the Content Blocks extension.

### Motivation

Blocksy is a great new upcoming theme that has a great user experience and lot's of customisation options while still being really fast.

**Comment by zauan** [comment]
We have contacted the Blocksy theme and provided them the code necessary for integrating Zion Builder into their theme. It should be available in their next update
