### ISSUE TITLE
Feature Request: Ability to change Icon Box spacer size

### ISSUE THREAD

**Issue by Infusednl** [zionbuilder/zionbuilder#383]
Dear support,

When using the Icon Box I noticed that there's an extra element with the classname 'zb-el-iconBox-spacer'.
See screenshot below:

<img width="434" alt="Schermafbeelding 2021-03-12 om 15 17 01" src="https://user-images.githubusercontent.com/6600256/110952452-89eea580-8346-11eb-83ec-b7b5704d424f.png">

However I couldn't find a way to change it's size through the Styling tab.
Can this be changed so we can edit the size of this spacer so we can control the spacing between the icon and the content?

## Summary

Ability to change the size of the Icon Box Spacer through the Styling Tab.

### Motivation

This let's us control the spacing between the icon and the content.

**Comment by zauan** [comment]
Will be available in next update
