### ISSUE TITLE
Bug: Can't change Icon background color (Icon Element)

### ISSUE THREAD

**Issue by Infusednl** [zionbuilder/zionbuilder#385]
Dear support,

I noticed that an option is missing inside the Icon element. In the screenshot below you can see two screenshots of the Icon element. As you can see we can setup an icon background but we can't set its color anywhere.

1. Icon element: General Options
<img width="418" alt="Schermafbeelding 2021-03-14 om 19 43 51" src="https://user-images.githubusercontent.com/6600256/111080209-ada81c00-84fd-11eb-831d-0c51870bfd1e.png">

2. Icon element: Icon Styles
<img width="416" alt="Schermafbeelding 2021-03-14 om 19 44 03" src="https://user-images.githubusercontent.com/6600256/111080211-b00a7600-84fd-11eb-8266-7a5b172a2b1e.png">

This happens only for the Icon element. The Icon List and Icon Box elements do allow us to change the background for an icon.

**Have you tried all the steps at https://zionbuilder.io/documentation/having-problems-using-zion-builder/?**
YES

**Steps to reproduce**
1. Add an icon element.
2. Set the style to filled.
3. Done. There should be no option visible that allows us to change the background.

**Expected behavior**
Setting the style to filled should show a new option for changing its background color.

**What actually happens**
The icon now has a background color which we can't change.

**Environment (please complete the following information):**
- OS: MacOS Big Sur 11.0.1.
- Browser: Chrome 89.0.4389.82
- Zionbuilder Free 2.0.0
- Zionbuilder Pro 2.0.0

**Comment by zauan** [comment]
Hi,

This will be added in the 2.1.0 update that will be released tomorrow
