### ISSUE TITLE
zionbuilder pro plugin not working

### ISSUE THREAD

**Issue by devotikuenne** [zionbuilder/zionbuilder#387]
<!--
  Please fill out each section below, otherwise, your issue will be closed. This info allows Zionbuilder maintainers to diagnose (and fix!) your issue as quickly as possible.

  Useful Links:
  - Documentation: https://zionbuilder.io/help-center/
I have a problem making zionbuilder pro work:

I have just made a clean install of wordpress 5.7.
I have installed the Zion Builder Plugin (v 2.0.0) and activated it.
Now I have installed Zion Buolder Pro (v 1.2.1) and activated it.

But instead of giving me the possibility to insert the license information, it gives me the warning:

"Zion builder Pro is not working because it requires the Zion builder plugin to be installed and active."

But the Zion builder plugin is active.
Can it be because of the different Versions (2.0.0 vs. 1.2.1)?
  
Thanks for your help!

**Environment**
- OS: MacOS 10.14.6
- Browser Firefox 86
- Zionbuilder Version [2.0.0]
- Zionbuilder Pro Version [1.2.1]

**Comment by zauan** [comment]
hi there,

Can you please give us more info about this? We have no reports regarding this matter

**Comment by devotikuenne** [comment]
Sure. What do you need?

**Comment by devotikuenne** [comment]
I have just installed the version 1.2.3 of Zion Builder. Now it works fine. Guess there is an incompatibility between Zion Builder 2.0.0 und Zion Builder pro 1.2.1…

**Comment by zauan** [comment]
Hi,

Indeed, the 2.0 version for both plugins are not fully compatible with the 1.1 version.

In case you have further problems, please don't hesitate to contact us.

Best regards,
Stefan
