### ISSUE TITLE
Bug: Section from library gets inserted inside the section above.

### ISSUE THREAD

**Issue by Infusednl** [zionbuilder/zionbuilder#402]
Dear support,

When I click on the dark blue Plus icon beneath a section to insert a saved section it get's placed inside the section above it. This only happens when I use the dark blue plus icon on the page itself. Through the Layers panel it gets inserted correctly:

Step 1. Click on the dark blue Plus icon to add a saved section from the library (User Blocks).
<img width="1839" alt="Schermafbeelding 2021-03-18 om 10 21 55" src="https://user-images.githubusercontent.com/6600256/111603117-4ecff480-87d4-11eb-9c8b-80d162aaa605.png">

2. As you can see it gets placed inside the section above it.
<img width="1840" alt="Schermafbeelding 2021-03-18 om 10 22 53" src="https://user-images.githubusercontent.com/6600256/111602963-2c3ddb80-87d4-11eb-90b2-ab4fbb764aa0.png">

This bug has been in Zion for as long as I use it and is still current in the latest public releases.

**Have you tried all the steps at https://zionbuilder.io/documentation/having-problems-using-zion-builder/?**
Yes

**Steps to reproduce**
1. Create a section and save it.
2. Go to any page that has sections already on it.
3. Place the saved section under any of the sections on the page.
4. The saved section will be placed inside the section that is above it.

**Expected behavior**
The builder should place the section beneath the section of where I clicked the blue Plus icon.

**What actually happens**
The section gets placed inside the section that is above it.

**Environment (please complete the following information):**
- OS: [e.g. Windows]
- Google Chrome 89.0.4389.90 (Officiële build) (x86_64)
- Zionbuilder Free Version 2.1.1
- Zionbuilder Pro Version 2.1.0

**Additional context**
This bug has been in Zion Builder for as long as I have been using. I didn't post it earlier as other bugs I needed to fix were more important.

**Comment by zauan** [comment]
Thanks for reporting this. It will be resolved in the next update
