### ISSUE TITLE
Bug: Custom Classes not added to Pagination Element.

### ISSUE THREAD

**Issue by Infusednl** [zionbuilder/zionbuilder#403]
Dear support,

When working with the Pagination Element I noticed that only the Wrapper contains my custom class.
The classes I added to the other Pagination elements are not being output in the html:

- Page Numbers Styling
- Current Page Styling
- Previous Text Styling
- Next Text Styling

<img width="343" alt="Schermafbeelding 2021-03-18 om 10 52 52" src="https://user-images.githubusercontent.com/6600256/111608659-c2283500-87d9-11eb-87a9-fbe9f0646663.png">

Here's a screenshot of the elements that don't get their custom class:

<img width="951" alt="Schermafbeelding 2021-03-18 om 10 53 05" src="https://user-images.githubusercontent.com/6600256/111608127-2b5b7880-87d9-11eb-9559-c17b9e6d4fa6.png">

Besides the class I added for the wrapper element gets output three times namely: be-pagination-wrapper.

**Describe the bug**
Pagination Element only inherits class for wrapper element. Besides this class also gets output three times.

**Have you tried all the steps at https://zionbuilder.io/documentation/having-problems-using-zion-builder/?**
Yes

**Steps to reproduce**
1. Add a pagination element
2. Add a class to each of the elements in the styling tab
3. Make some changes and save.
4. View the page and only the wrapper element should inherit its class times 3.

**Expected behavior**
Each class for the pagination element should be output.

**What actually happens**
Only the wrapper element inherits its class and outputs it three times.

**Screenshots/Videos**
See the above screenshots

**Environment (please complete the following information):**
- OS: [e.g. Windows]
- Google Chrome 89.0.4389.90 (Officiële build) (x86_64)
- Zionbuilder Free Version 2.1.1
- Zionbuilder Pro Version 2.1.0

**Comment by zauan** [comment]
Hi there, the duplicated class name will be resolved in the next update ( it was introduced in the beta version I've sent ).

Regarding custom classes not adding, this is something that we cannot fix as the HTML markup is generated by WP functions like paginate_links and get_next_posts_link.

In the next update, the option to add custom css classes and custom render attributes will be disabled so there won't be any confusion about this
