### ISSUE TITLE
Bug: Pagination still present even when there are not enough posts to paginate

### ISSUE THREAD

**Issue by Infusednl** [zionbuilder/zionbuilder#404]
Dear support,

I noticed that the pagination element is still present, even when there are not enough elements to paginate.
I used margin-top to offset the element from the posts. But since there are not enough the pagination is not visible, however the wrapper element with the margin is still there.

Is it possible to hide it completely when there are not enough elements?

**Have you tried all the steps at https://zionbuilder.io/documentation/having-problems-using-zion-builder/?**
Yes

**Steps to reproduce**
See the description above.

**Expected behavior**
Pagination should be hidden completely from the output.

**What actually happens**
Pagination wrapper element: <nav> is still present.

**Screenshots/Videos**

1. Here you can see the empty <nav> still being output:
<img width="581" alt="Schermafbeelding 2021-03-18 om 11 59 36" src="https://user-images.githubusercontent.com/6600256/111616385-1d5e2580-87e2-11eb-89eb-092c1123201d.png">

2. Here you can see the element still takes up space with its margin top:
<img width="1362" alt="Schermafbeelding 2021-03-18 om 11 59 42" src="https://user-images.githubusercontent.com/6600256/111616472-37980380-87e2-11eb-828c-4cbc6b009163.png">

**Environment (please complete the following information):**
- OS: [e.g. Windows]
- Google Chrome 89.0.4389.90 (Officiële build) (x86_64)
- Zionbuilder Free Version 2.1.1
- Zionbuilder Pro Version 2.1.0

**Comment by zauan** [comment]
This will be implemented in the next update
