### ISSUE TITLE
Feature Request: Create seperate Single template for each taxonomy

### ISSUE THREAD

**Issue by Infusednl** [zionbuilder/zionbuilder#407]
Dear support,

At the moment we can create one Single template for each post type. However I would like to be able to create multiple Single template for a post type based on Taxonomy.

For example, I have a post type called Motorcycles. Now I need to create two seperate templates for displaying a single motorcycle based on it's taxonomy which can be: New or Occasion.

As of now this is not possible since we can't differentiate based on Taxonomy.

## Summary

Abillity to create different templates for displaying a single post type based on it's taxonomy.

### Motivation

Allow for more creative freedom to display a single post type based on it's taxonomy.

**Comment by zauan** [comment]
This will be available in the next update
