### ISSUE TITLE
Shape Dividers are not displayed on the front end

### ISSUE THREAD

**Issue by michael-grunewalder** [zionbuilder/zionbuilder#430]
**Describe the bug**
When i add a shape divider to a section, ti shows in the backend (editor) but not in the front end after publishing and previewing the page.

**Have you tried all the steps at https://zionbuilder.io/documentation/having-problems-using-zion-builder/?**
Yes

**Steps to reproduce**
add a shape divider to a section or import a library item with a shape divider.
Save + Publish
Preview the page

**Expected behavior**
the section should have the shape divider

**What actually happens**
The section does not have the shape divider

**Screenshots/Videos**
Editor (Backend)
<img width="500" alt="CleanShot 2021-04-02 at 16 06 35@2x" src="https://user-images.githubusercontent.com/59302840/113400104-e2f4ab00-93d3-11eb-9124-d9c22ad690e0.png">

Front End:
<img width="500" alt="CleanShot 2021-04-02 at 16 06 51@2x" src="https://user-images.githubusercontent.com/59302840/113400215-0881b480-93d4-11eb-9eab-e7e82c29288b.png">

**Environment (please complete the following information):**
- OS: MacOS
- Browser Firefox / Chrome (latest versions)
- Zionbuilder Version 2.1.1 (Pro 2.1.0)

**Comment by zauan** [comment]
Hi there,

Sorry for the late reply, for some reason I've missed this ticket. Can you please confirm you still have this problem with the 2.4.1 versions? There was a problem related to masks in an older version which should be resolved now.

**Comment by jayjay9000** [comment]
I have the same issue with version 2.7.1 (Pro). Is there any solution available yet?

**Comment by tweschke** [comment]
I have the same issue still.
I'm running the latest version 2.7.3 (PRO) with WP 5.8, PHP 7.4. I've tested this now on a clean install on my MAMP PRO 6.5 lab and I get the same results.

When can we expect a fix for this issue, as this impacts users design ideas/plans?!?!

**Comment by zauan** [comment]
Hi guys,

We have tracked this problem down and it will be resolved in the next update. It seems that this is related to a server setting.

Best regards,
Stefan
