### ISSUE TITLE
Featured Request: Better Native Navigation

### ISSUE THREAD

**Issue by rindoshingen** [zionbuilder/zionbuilder#432]
Hey folks, 

First off, love this plugin. Clean, fast, not bloated with unneeded code, super clean UI - well done. 

However, I was wondering you could build on or extend the native navigation function? Right now there is none. Your demos show navigation being built with "buttons" ... but this does not allow for dropdown or submenus - therefore the whole native Wordpress navigation via the dashboard doesn't work. 

Cheers

**Comment by zauan** [comment]
Hi there,

Thanks for the feedback. As a matter of fact, a part of our team is working on a menu element and also, mega menu capabilities. This should be available in 2-3 weeks

**Comment by rindoshingen** [comment]
Hey there, 

This is awesome news ... looking forward to this. Keep up the excellent work, fantastic plugin! =)

Cheers

**Comment by zauan** [comment]
Hi,

Navigation element and mega menu functionality was implemented in v2.4.0
