### ISSUE TITLE
Feature Request: Control Child Elements through a Parent Element.

### ISSUE THREAD

**Issue by Infusednl** [zionbuilder/zionbuilder#437]
Dear support,

I would like to request a feature that hasn't been implemented by any builder so far (At least not to my knowledge).

What I would like to do is to control the CSS properties of child elements through the parent. This way child elements can have very basic class names.

Example of a simple blog post that could be used in a repeater:

    <div class="blog-post">
        <div class="inner">
            <img class="post-img" src="/img.jpg" >
            <h2 class="title">Post Title</h2>
            <div class="content">
                <p>Lorem ipsum dolor sit amet...</p>
            </div>
        </div>
    </div>

With the current Zion Builder we have to write very specific CSS classes since we can't target elements from the parent.
So the following is what I would like to do but isn't possible as of yet:

.blog-post .inner {
    // Some CSS...
}

.blog-post .post-img {
    // Some CSS...
}

.blog-post .title {
    // Some CSS...
}

.blog-post .content {
    // Some CSS...
}

.blog-post .content p {
    // Some CSS...
}

The above example allows us to reuse simple CSS classnames without adding any style directly to an element. Besides this allows us also to control each element from the parent.

As of now we can add custom pseudo selectors (https://zionbuilder.io/documentation/css-pseudo-class-selectors/). If possible I would like this to support adding child selectors.

If this is possible then we could also manipulate child elements when we hover over the parent by adding a pseudo selector like:

.blog-post:hover .post-img { //Some CSS code }

## Summary

Ability to target child elements from a parent. This is not possible as of yet so we have to resort to adding custom css in either the Customizer or via a plugin.

### Motivation

This is in my opinion a must-have feature for creating complicated layouts and makes management easier since we can control all child elements from the parent.

**Comment by zauan** [comment]
This was implemented and will be available in the 2.3.0 update
