### ISSUE TITLE
Bug in the editor after adding a class to a column

### ISSUE THREAD

**Issue by codemyart** [zionbuilder/zionbuilder#447]
Hello,

I found a bug when I add a class to the column. The editor preview is breaking, but not affect on the published page.
You could download the video from:

https://dox.abv.bg/download?id=3084d8cdd2

I hope it is usable to you.

Best regards,
George Dramcheff

**Describe the bug**
*Write a explanatory description of the bug.*

**Have you tried all the steps at https://zionbuilder.io/documentation/having-problems-using-zion-builder/?**
*Yes/No*

**Steps to reproduce**

**Expected behavior**
*What should have happend after following the steps above.*

**What actually happens**
*Provide a concise message of what is actually happening.*

**Screenshots/Videos**
*If applicable, add screenshots/videos to help explain the problem.*

**Environment (please complete the following information):**
- OS: [e.g. Windows]
- Browser [e.g. chrome version 50, IE11]
- Zionbuilder Version [e.g. 1.0.0]

**Additional context**
*Add any other context about the problem here.*

**Comment by zauan** [comment]
Hi,

Just wanted to let you know that this was resolved and the fix will be included in the next update.

Thank you,
Stefan
