### ISSUE TITLE
Repeater duplicate ID-s

### ISSUE THREAD

**Issue by codemyart** [zionbuilder/zionbuilder#449]
Hello,

Inspecting the output code of the repeater I see, there is a problem like in Oxygen - all elements have the same ID. It is huge problem. Your repeater is a new element and the time to repair that is just now. Oxygen customers looking for some workaround from years, but Oxygen tem don't matter this problem, I don't know why. It is a serious problem, because you canot point to different elements via javascript or just to point some anchor. If you have more repeaters (like in my last website) it makes a real mess. Ih you have one or two, there is some solutions like https://conlumina.com/fix-oxygen-repeater-duplicate-ids/

**Comment by zauan** [comment]
Hi there,

Thank you for reporting this. Actually, this is one of the things that separates us from other page builders. The repeater items have their own unique id's, and all the styling is done based on a css class,

By doing this, there are two benefits:

- The elements have unique ID's which is a valid HTML markup
- The css is only generated once

You can see this in the image bellow: 

![image](https://user-images.githubusercontent.com/5928748/115681567-53e90c00-a35d-11eb-8d3b-4bf6df17e65b.png)

Can you please check and let me know if this is not the case on your end so we can investigate?

**Comment by codemyart** [comment]
Sorry, I haven't seen the indexing. Wondersul solution, thank you! :)

**Comment by zauan** [comment]
You're welcome! If you have any other feedback , please don't hesitate to contact us
