### ISSUE TITLE
Text size, Margin and Padding values

### ISSUE THREAD

**Issue by codemyart** [zionbuilder/zionbuilder#461]
Hello,
In Oxygen builder there is a new possibiity to remove the signs after the font size, margin, padding values like %, px, vh and so on. You just choose none (new added) and in the text field of the value you can fill the clamp function. This is extremly useful for responsiveness. I hope this feature could be add to Zion.
Thanks in advance and best regards,

**Comment by zauan** [comment]
Hi there,

Thank you for opening this ticket. In Zion Builder this feature was implemented in the first release. On the right side of a size option, you will need to press the three dots and choose custom. This will let you set any value you want, including calc functions

![image](https://user-images.githubusercontent.com/5928748/117996323-baed5580-b34a-11eb-84fe-c306632ec6fd.png)
