### ISSUE TITLE
Feature Request: Allow CSS properties such as Transform Scale to have 2 decimal values.

### ISSUE THREAD

**Issue by Infusednl** [zionbuilder/zionbuilder#462]
Dear support,

I noticed that some properties can only have 1 decimal number behind the komma.
One such property is the transform. I noticed this when I added transform and then Scale to an item.

I wanted to create a hover effect by using this transform Scale with a value of 1.05 so it's nice and subtle.
However Zion Builder only allows for 1 decimal numbers. Because of this I had to use 1.1 for my scale which looks too big.

Please allow the use of two decimal numbers so we can create more fine-tuned layouts and effects.

## Summary

Please allow the use of two decimal values to be input for all CSS properties that accept decimal numbers such as the Transform options.

### Motivation

Allow more precise values to be used inside Zion Builder. Sometimes like with Transform Scale 1.1 is too much and something like 1.05 is perfect for a subtle hover effect.

**Comment by zauan** [comment]
Hi,

This will be available in v2.4.1. There isn't a general option to enable this on all options. In case you need this type of precision for other options, please let us know.

best regards,
Stefan
