### ISSUE TITLE
Feature Request: Integration of FacetWP or perhaps Zion's own implementation of live Search Filters

### ISSUE THREAD

**Issue by Infusednl** [zionbuilder/zionbuilder#463]
Dear support,

For one client I had to integrate FacetWP (https://facetwp.com/). I have setup everything correctly but for some reason FacetWP can't alter the loop of a Repeater Provider although the FacetWP filters show up nicely.

Another solution could be that Zion Builder has it's own filter element (Which I would definitely prefer above FacetWP).
What I would like to do is to be able to create filters that can filter any Repeater Provider like this example on the FacetWP website: https://facetwp.com/demo/cars/.

## Summary

Add the abillity to create search filters that can live filter our post grids, archive pages etc.
Here I would like to be able to create the following type of filters:

- Checkbox
- Dropdown
- Multi-Select
- Searchbox (I think we already have this one in Zion Builder)
- Range Slider

### Motivation

This allows us to create listings that users can filter. For now I use FacetWP with their own grid builder, however this grid builder is fairly basic and I would like to be able to do this in Zion Builder.

**Comment by zauan** [comment]
Facet WP integration will become available in version 2.5.0
