### ISSUE TITLE
PHP function to return a custom field value

### ISSUE THREAD

**Issue by jorodr** [zionbuilder/zionbuilder#494]
Hello,
Is it possible to add a possibility for choosing a php function that returns a data from a custom field in custom fields options? Need two fields - one for the function name and one for the parameters. So  we can pass to function a parameter which field we need. Thanks.

**Comment by zauan** [comment]
Hi there,

Thanks for contacting us. Are you referring to the dynamic data? If so, there is already a "Function return value" field as seen in the attached image

![image](https://user-images.githubusercontent.com/5928748/119817226-62938780-bef6-11eb-8e89-aaae9ee72fb4.png)

**Comment by jorodr** [comment]
Hello,

That I mean, but why my context menu is different?
What I'm doing wrong?

![zion-meta](https://user-images.githubusercontent.com/26181536/119842650-86af9280-bf0f-11eb-8d53-b238608cb48b.jpg)

**Comment by jorodr** [comment]
Hello

Yes, sorry, I saw it on text element, but can you add it to anywhere we could use dynamic data. As link URL and image source.

Thank you in advance

**Comment by zauan** [comment]
Hi, 

just wanted to let you know that the "Function return value" dynamic field will be added to all field types in the next update.

Best regards,
Stefan
