### ISSUE TITLE
Bug: Value of 0 not getting output when used on border without the px suffix

### ISSUE THREAD

**Issue by Infusednl** [zionbuilder/zionbuilder#496]
Dear support,

I have a class that has a border-right of 1px for multiple elements in the same container.
Then I wanted to remove this border for the last child of this class by using the custom selector :last-child.

However I noticed that when I use just 0 as a value it doesn't get output. Only when I use 0px my CSS gets output.
Please make it so we can use 0 as it is a valid CSS value.

**Have you tried all the steps at https://zionbuilder.io/documentation/having-problems-using-zion-builder/?**
Yes

**Steps to reproduce**
1. Add a column and add some child elements that have a class that contains border-right: 1px.
2. Then add a custom CSS selector :last-child and remove the border by putting in just a 0.
3. Inside the builder the border should be gone, however when you view the page the border is still present on the last child as the CSS is not getting output.
4. Now on the :last-child selector add a value of 0px on the border-right instead of just a 0.
5. Now the border should be gone in both the builder and the front-end.

**Expected behavior**
The border on the last child should be gone on the front-end once you use 0 as a value.

**What actually happens**
The CSS for the border-right only gets output when you use a suffix such as px.

**Environment (please complete the following information):**
- MacOS 11.0.1
- Chrome 90.0.4430.212
- Zionbuilder Free & Pro v2.4.1

**Comment by zauan** [comment]
This will be resolved in the next update
