### ISSUE TITLE
Bug: Slider Builder not displaying correctly on Windows

### ISSUE THREAD

**Issue by Infusednl** [zionbuilder/zionbuilder#497]
Dear support,

I have created a Logo carousel by using the Slider Builder. In Chrome on Mac it looks precisely as intended but on Windows it looks awful as if al my classes are not working.

Here's a screenshot on my Mac, exactly as it should be:
<img width="1216" alt="Schermafbeelding 2021-05-28 om 15 49 55" src="https://user-images.githubusercontent.com/6600256/119993890-5d087100-bfcc-11eb-8a1e-29818fb6f5c4.png">

Below is how it looks on Windows on both my other laptop as on my clients Windows computer:
![image](https://user-images.githubusercontent.com/6600256/119994746-2c750700-bfcd-11eb-9f8c-15a31e1ae68d.png)

All classes are in through the Global CSS Classes where I utilised the new Child Selectors.

**Describe the bug**
The Slider Builder works great on Mac but looks awful on Windows. Both checked in the latest Google Chrome.
This happens on two different Windows machine.

**Have you tried all the steps at https://zionbuilder.io/documentation/having-problems-using-zion-builder/?**
Yes.

**Steps to reproduce**
1. Add a Slider Builder
2. Add some classes and style it with Child Selectors.
3. On mac everything looks fine but not on Windows.

**Expected behavior**
The Slider Builder should look the same on both Mac and Windows.

**What actually happens**
On Windows in Chrome the styles are not applied.

**Screenshots/Videos**
See my message above.

**Environment (please complete the following information):**
- Windows 10
- Latest Google Chrome.
- Zionbuilder Free & Pro 2.4.1.

**Additional context**
I can give access to the website in a private mail/chat. Please let me know when you have the time.

**Comment by Infusednl** [comment]
I just tested it out but the slider also doesn't show up correctly in other browsers on MacOS. So it's not just a Windows thing unfortunately. So far it only works perfectly on Chrome on Mac.

**Comment by zauan** [comment]
The problem was generated by a caching plugin that didn't remake the cache files properly
