### ISSUE TITLE
Bug: FacetWP with Repeater shows only 10 posts

### ISSUE THREAD

**Issue by Infusednl** [zionbuilder/zionbuilder#500]
Dear support,

I just created a Repeater listing that can be filtered with FacetWP. All works well except it shows 10 posts max.
Even when there are more posts to be shown it never exceeds 10.

In the Wordpress Reading settings I have set my posts to show at 30. How can we adjust this so it shows all posts and not just 10?

You can view this bug at: https://devoswerkt.nl/vacatures/

**Describe the bug**
The FacetWP works perfect except it shows 10 posts at max, even when there are more posts available. I would like to remove this 10 post limit so it shows all posts.

**Have you tried all the steps at https://zionbuilder.io/documentation/having-problems-using-zion-builder/?**
Yes

**Steps to reproduce**
1. Create an Archive page.
2. Create a repeater listing using the Repeater provider.
3. Add FacetWP filters.
4. No matter how many posts are available it will only show 10 at max.

**Expected behavior**
The Repeater should show all posts.

**What actually happens**
*Provide a concise message of what is actually happening.*

**Screenshots/Videos**
*If applicable, add screenshots/videos to help explain the problem.*

**Environment (please complete the following information):**
- MacOS Big Sur 11.0.1
- Chrome 91.0.4472.77
- Zionbuilder Free & Pro 2.4.1 experimental built with FacetWP Integration

**Additional context**
If needed I can provide Admin access. The website can be viewed at: https://devoswerkt.nl/vacatures/

**Comment by zauan** [comment]
Upon investigations, it seems that the problem was coming from a setting In the Blocksy theme that forces by default 10 posts per page regardless of the WP setting
