### ISSUE TITLE
Bug: Zion Builder Pages get randomly deleted after saving!!!

### ISSUE THREAD

**Issue by Infusednl** [zionbuilder/zionbuilder#501]
Dear support,

A little while ago I spoke with Stefan about Custom Post Type posts being randomly deleted after I was working on them.

However just now I was working on the homepage of a new website. I worked on it for quite some time without any problems until today. I was working in Zion Builder using just the ZB element when I hit save and clicked on 'View Post' and got redirected to a 404 Error page!

Luckily I always open them in a new tab. Because of this I had the homepage still opened in Zion Builder so I could quickly save all my sections to the library as a backup solution.

Please make this an urgent issue as it has te be resolved quickly. This issue already costed me lots of hours and I don't even want to think about what happens if this occurs when one of my client edits a page in Zion Builder.

**Describe the bug**
Any page or custom post type that has Zion Builder enabled can be deleted randomly when saving and viewing the post.
Again, it happens randomly.

However, when it does happen, I always did the following:

1. I saved my page after editing.
2. I right-click on 'View Post' in the blue Zion Builder toolbar on the left and select: 'Open in New Tab'.

**Have you tried all the steps at https://zionbuilder.io/documentation/having-problems-using-zion-builder/?**
Yes

**Steps to reproduce**
1. I saved my page after editing.
2. I right-click on 'View Post' in the blue Zion Builder toolbar on the left and select: 'Open in New Tab'.
3. If you're unlucky you get redirected to a 404 Error page and the page is gone.
4. At least for custom post types I noticed that the permalink for the deleted posts is still taken as if the deleted post is still present somewhere in the Wordpress database.

**Expected behavior**
Pages and Custom Post Type posts shouldn't get deleted upon saving.

**What actually happens**
My pages and posts get deleted randomly.

**Screenshots/Videos**
N/A. When this happens I just see my theme's 404 Error page.

**Environment (please complete the following information):**
- MacOS Big Sur 11.0.1
- Chrome 91.0.4472.77 (Officiële build) (x86_64)
- Zionbuilder Free & Pro 2.4.1

**Additional context**
This bug has happened on various websites of mine that use the same basic setup.
Almost identical plugins but all use the Blocksy theme with Pro extension.

**Comment by zauan** [comment]
This should be resolved in v2.5.0
