### ISSUE TITLE
Bug: Slider Builder & Image Slider - Slides to Show input is not responsive

### ISSUE THREAD

**Issue by Infusednl** [zionbuilder/zionbuilder#502]
Dear support,

The Slider Builder and Image Slider both have an input option called: Slides to Show.
However this setting can't be change for each viewport.

If I select 6 slides to show on desktop then it will also show 6 sliders on tablet and mobile.

**Describe the bug**
Slides to Show option can't be changed per viewport.

**Have you tried all the steps at https://zionbuilder.io/documentation/having-problems-using-zion-builder/?**
Yes

**Steps to reproduce**
1. Add a Slider Builder or Image slider.
2. Fill it with slides.
3. Set the Slides to show to any number.
4. Changing this option will change it for all viewports.

**Expected behavior**
Being able to change the Slides to Show per viewport.

**What actually happens**
You can only setup one value for all viewports.

**Screenshots/Videos**
N/A

**Environment (please complete the following information):**
- MacOS Big Sur 11.0.1
- Chrome 91.0.4472.77
- Zionbuilder Free & Pro 2.4.1

**Additional context**
N/A

**Comment by zauan** [comment]
This will be resolved in the next update
