### ISSUE TITLE
Bug: Disabling autoplay for Image Slider element not working

### ISSUE THREAD

**Issue by Infusednl** [zionbuilder/zionbuilder#504]
Dear support,

The autoplay function of the Image Slider element doesn't work as it always auto plays on my end.
Even when disabled it still autoplays.

Please fix this so it adheres to the setting we setup.

**Describe the bug**
The Image Slider always autoplays, even when this option is disabled.

**Have you tried all the steps at https://zionbuilder.io/documentation/having-problems-using-zion-builder/?**
Yes

**Steps to reproduce**
1. Create a page and add the Image Slider.
2. Add some images and disable Autoplay.
3. On both the frontend as in the Builder itself the Image slider keeps autoplaying.

**Expected behavior**
The Image Slider should not autoplay when we disable this in the settings.

**What actually happens**
The Image Slider is stuck on autoplay.

**Screenshots/Videos**
I can provide the url plus admin access so this can be viewed in action.

**Environment (please complete the following information):**
- MacOS Big Sur 11.0.1
- Chrome 91.0.4472.77
- Zionbuilder Free & Pro 2.4.1

**Additional context**
N/A

**Comment by zauan** [comment]
Hi there, 

Just wanted to let you know that this will be resolved in v2.5.0
