### ISSUE TITLE
Google Maps doesn't go full width

### ISSUE THREAD

**Issue by SebastianHase** [zionbuilder/zionbuilder#513]
Hello, 

I got some issues with the google maps element. It just doesn't go full width like in your description: https://zionbuilder.io/documentation/google-maps/
it is always with margins :( see attachment

If I choose a fullwidth template for the page, it goes in fullwidth but all my margins are lost. The Slider Revolution objects just go in full width, no matter what template I use. How can I get the same effect on the maps element? 
(Just changing the size in pixels doesn't seem like a proper solution for me.)

Zionbuilder version is 2.3.1, I use chrome on a mac. 

Please help me out
Best regards,
Sebastian

![Bildschirmfoto 2021-06-09 um 19 44 14](https://user-images.githubusercontent.com/85640236/121403436-2da61c80-c95b-11eb-879f-60355e99a5b1.png)

**Comment by zauan** [comment]
Hi there,

In the documentation article we have used the Full width template. From what I understand, this is not ok for your layout so the only way to make the map full width would be to use the following css:

```
#mapElementID {
  width: 100vw;
  position: relative;
  left: 50%;
  right: 50%;
  margin-left: -50vw;
  margin-right: -50vw;
}
```

This will make the google map exit it's container and expand to full width.

Please let me know if this worked

**Comment by SebastianHase** [comment]
Hey Zauan, 

you made my day! Thank you very much :)

Best regards,
Sebastian

**Comment by zauan** [comment]
Great! 

I will now close this ticket!

if you need further help, please let me know

best regards,
Stefan
