### ISSUE TITLE
Feature Request: Display Post Terms (Dynamic Data Option) in hierarchical order instead of alphabetical order

### ISSUE THREAD

**Issue by Infusednl** [zionbuilder/zionbuilder#516]
Dear support,

I noticed that when we use the Post Terms (Dynamic Data) option in for example a Text Element, that the post terms are output in alphabetical order instead of adhering to the Hierarchical order we setup in Wordpress.

Can this be changed so we can show Post Terms in hierarchical order or reversed Hierarchical order? Like for example show an extra dropdown or selectbox thats says something like:

O - Enable Alphabetical Order
O - Enable Hierarchical Order
O - Enable Reverse Hierarchical Order

##Real World Usecase##
One of my client websites has a Custom Post Type for Vacatures ('Job offerings' in Dutch).
For this post type I created a custom taxonomy called Locations.
This Locations taxonomy has 12 parent categories, one for each Province of The Netherlands.
Then each city is added as a child category to the right Province parent category.

I created a grid that shows all Job offerings in a card style with various information below the title.
One of these is the location so potential candidates can see where each job offering is located.

At the moment it displays all locations in alphabetical order. Because of this the Province and City are swapped on some job offers. So instead of:

- Ruurlo (City), Gelderland (Province)

Some job offerings are displayed as:

- Gelderland (Province), Ruurlo (City)

I would like to display the city (Child Category) first, then the Province (Parent Category), Example:

- Ruurlo (City first), Gelderland (Province last).

Below is a screenshot of the issue I'm encountering:

<img width="621" alt="Schermafbeelding 2021-06-11 om 12 30 02" src="https://user-images.githubusercontent.com/6600256/121676838-68bc6300-cab5-11eb-8bfc-fec775d3a988.png">

Below here is a screenshot of the Post Terms dynamic option which I am using to retrieve my Locations custom taxonomy:

<img width="529" alt="Schermafbeelding 2021-06-11 om 12 29 42" src="https://user-images.githubusercontent.com/6600256/121676930-87225e80-cab5-11eb-88ef-d1d121b905cb.png">

## Summary

Add an option so we can display Post Terms in hierarchical or reversed hierarchical order instead of the default alphabetical order.

### Motivation

Give us the freedom to display Post Terms in the order we need. :)

**Comment by zauan** [comment]
Hi there,

Unfortunately, WordPress doesn't provide an easy way to display the post terms by hierarchy ( without making additional database queries or multiple loops ). The next best thing is to add two options:
- Order By
- Order

In order to achieve your desired order, you could select the Order By option to 'Term id'.

This will be available in the next update
