### ISSUE TITLE
Bug: Any code I put in Page Options => Custom JS does not get compiled/output

### ISSUE THREAD

**Issue by Infusednl** [zionbuilder/zionbuilder#520]
Dear support,

For the last few versions I noticed that my custom Javascript code is not being compiled when I store it at Page Options => Custom JS.

I updated to the latest available which is Zion Builder Free & Pro 2.5.0-rc1. However this made no difference. Even a simple console.log('Hello World'); doesn't get output.

I disabled WP Fastest Cache and cleared it's cache just to be sure. I also cleared and regenerated the Zion Builder cache multiple times and I cleared my browser cache multiple times, however the problem still persists.

I also disabled all plugins except Zion Builder Free & Pro but the problem still persisted. :/

**Describe the bug**
Custom JS inside Page Options is not being compiled.

**Have you tried all the steps at https://zionbuilder.io/documentation/having-problems-using-zion-builder/?**
Yes

**Steps to reproduce**
1. On mac, in Google Chrome add some javascript like console.log('hello world'); at Page Options => Custom JS
2. Save the page and view it on the frontend.
3. Check the console log to see if your JS works/shows up, mine doesn't.

**Expected behavior**
To be able to use the Custom JS field. Since the last few versions this problem has persisted.

**What actually happens**
My code doesn't get output to the page.

**Screenshots/Videos**
Here's my Javascript:
<img width="345" alt="Schermafbeelding 2021-06-13 om 00 55 10" src="https://user-images.githubusercontent.com/6600256/121790695-1af14900-cbe2-11eb-8902-5a1f4d03706f.png">

On the frontend this is all I see in my browser console:
<img width="1440" alt="Schermafbeelding 2021-06-13 om 00 55 23" src="https://user-images.githubusercontent.com/6600256/121790701-32c8cd00-cbe2-11eb-97b3-aa7d3f4dae54.png">

No console.log or whatsoever.

**Environment (please complete the following information):**
- OSX Big Sur 11.0.1
- Chrome 91.0.4472.101 (Officiële build) (x86_64)
- Zionbuilder Free & Pro 2.5.0-rc1

**Comment by zauan** [comment]
This will be resolved in the upcoming update
