### ISSUE TITLE
Before the purchase

### ISSUE THREAD

**Issue by roman75323** [zionbuilder/zionbuilder#526]
Good afternoon, Zion team.  For some time I have been considering a zion builder to buy.  I follow the updates, and most importantly, the feedback.
Demotivation:
I see that GitHub support has been responding to user requests for a rather long time.  I don't know what happens to the tickets of those who bought this plugin.  I don’t pay attention to the shortcomings (it’s clear that it takes time).  I would like to see more responsive support across all community resources from your team.  I'll think about it for another week.  This is not a bad review, but a check for availability and feedback.  Thank you.

**Comment by zauan** [comment]
hi there!

Thank you for your interest in our builder. Indeed, we are most active on the Facebook community page than on Github.

Please note that this doesn't mean that we do not check the GitHub pages, however, many of the tickets opened are created by a single client with who we are also communicating outside Github ( so this is why we do not reply to all tickets ).

For any bug related ticket, we try to resolve the bug in the next plugin update ( except for one bug that we have totally missed from January :( )

Please let me know if you have further questions or concerns.

Best regards,
Stefan
