### ISSUE TITLE
🐛 Header & Footer Issue

### ISSUE THREAD

**Issue by Albena-Abigail-Karaivanova** [zionbuilder/zionbuilder#530]
I have a problem when creating a Header & Footer for my website. I need to make an entire new Template to make a header, that applies to the website. And now I see even then this template is not applied on the new page that I created after that. 

![image1](https://user-images.githubusercontent.com/75545103/122371670-b5e27e00-cf68-11eb-85a8-8a51043bc928.png)

I have the new Header applied on yesterday's created page, but it is not applied on the page I created today.

https://zion.aless-design.com/home/ 

![image4](https://user-images.githubusercontent.com/75545103/122371814-d4e11000-cf68-11eb-9e83-1304c79ce042.png)

https://zion.aless-design.com/zionbuilder-322/

![image5](https://user-images.githubusercontent.com/75545103/122371855-df030e80-cf68-11eb-8f96-021435af8b39.png)

This problem applies to the footer as well. 

When I make the new page I see the Header

![image3](https://user-images.githubusercontent.com/75545103/122372010-fe9a3700-cf68-11eb-9608-e312de37ac8d.png)

But when I need to make the page as a blank canvas to start my design it disappears. 

![Screenshot](https://user-images.githubusercontent.com/75545103/122372606-79fbe880-cf69-11eb-8719-eb0ca99127ad.png)

**Comment by zauan** [comment]
Hi there,

Thank you for contacting us. The blank canvas option hides the header and footer and only shows the content made with the page builder.

If you want to keep the header and footer, please choose the Zion Builder Full-Width template as this will keep the header and footer while providing you a full-width page.

If there is a different problem, please give me more information.

Best regards,
Stefan

**Comment by Albena-Abigail-Karaivanova** [comment]
Hi, Stefan! Thank you so much for the answer! It works perfectly and solved my problem! 

Best regards, 
Albena
