### ISSUE TITLE
🐛 Mega menu issue

### ISSUE THREAD

**Issue by Albena-Abigail-Karaivanova** [zionbuilder/zionbuilder#545]
Hi, today I was exploring the mega menu features. I followed your article for creating a mega menu and came across 2 major problems. 

1. When I finished creating my mega menu, the display tab did not work:

![Mega menu](https://user-images.githubusercontent.com/75545103/123068327-76111000-d41a-11eb-8d93-5b1f2e08a5ea.png)

2. After all I saved the changes for my mega menu "deleted" all my page designs.

![Mega menu 2](https://user-images.githubusercontent.com/75545103/123068622-b8d2e800-d41a-11eb-8b64-dda08d0605d6.png)

Thank you!

**Comment by zauan** [comment]
Hi there,

Thank you for submitting this issue. Both problems were resolved in v2.7.1 If you still experience problems, please don;t hesitate to reopen this ticket and provide additional information
