### ISSUE TITLE
H1 Got Issue

### ISSUE THREAD

**Issue by jamaalhassan** [zionbuilder/zionbuilder#549]
**Describe the bug**
*Write a explanatory description of the bug.*
the h1 is behaviour like h2 and h1 has margin spacing bottom I cant see properly I think 24px has a default shouldn't be it. you can see screen record
https://app.usebubbles.com/6pqAFoGY6gj9BVZQSCX8P8/comments-on-qurxinta-com

**Have you tried all the steps at https://zionbuilder.io/documentation/having-problems-using-zion-builder/?**
*Yes*

**Steps to reproduce**
Steps to reproduce the behaviour:

**Expected behavior**
*What should have happend after following the steps above.*

**What actually happens**
*Provide a concise message of what is actually happening.*

**Screenshots/Videos**
*If applicable, add screenshots/videos to help explain the problem.*
https://app.usebubbles.com/6pqAFoGY6gj9BVZQSCX8P8/comments-on-qurxinta-com

**Environment (please complete the following information):**
- OS: [ Windows 10 laptop]
- Browser [Microsoft Edge
Version 91.0.864.54 (Official build) (64-bit)
- Zionbuilder Version [2.6.1]

**Additional context**
*Add any other context about the problem here.*
==Server environment==
	operating system: Linux
	software: LiteSpeed
	mysql version: MariaDB Server v10.3.29
	php version: 7.2.34
	php max input vars: 3000
	php max post size: 1024M
	gd installed: Yes
	zip installed: Yes
	write permissions: All right
==WordPress environment==
	version: 5.7.2
	site url:*******************
	home url: ****************
	wp multisite: No
	max upload size: 1 GB
	memory limit: 40M
	permalink structure: /%postname%/
	language: en-US
	timezone: 0
	admin email:*******************
	debug mode: Inactive
==Theme==
	name: Twenty Twenty-One
	version: 1.3
	author: the WordPress team
	child theme: No
==Active plugins==
	Zion Builder
	Zion Builder Pro

**Comment by zauan** [comment]
Hi there,

thank you for contacting us. From what I see in the video the margin is set by your theme and get removed when you set the margin to 0px in the editor. To be honest, I do not see any problem with this as this is the correct behavior. The builder uses the theme styles by default.

If you still consider this to be a bug, can you please give me more information?

**Comment by jamaalhassan** [comment]
this is my first time using zion builder I didn't know the theme can interact with the Zion Builder element such as h1. do you guys have someplace that tells me which theme does support the zion builder 100% in the video I also showed h1 behaving like h2 and h2 acting like h1 have you seen those two?

**Comment by zauan** [comment]
Hi there,

the builder should work with any theme and should follow the theme styles for general markup (.including headings ). At the moment, we are recommending the Blocksy theme until we release our own theme.
