### ISSUE TITLE
Right click edit disappears after moving mouse onto options

### ISSUE THREAD

**Issue by interlogic0** [zionbuilder/zionbuilder#558]
**Describe the bug**
*When scrolling to the bottom of the page and right clicking on an element to bring up the context menu then hovering over the menu, the menu disappears as soon as you touch the menu* You can see an example at https://youtu.be/5VYkRpWBqKM

I only encountered this issue after creating enough content to fill the screen and needing to scroll to see/edit/add more content/sections etc.

**Have you tried all the steps at https://zionbuilder.io/documentation/having-problems-using-zion-builder/?**
*Yes*

**Steps to reproduce**
1. Create enough content to fill the page (sections or elements)
2. Right Click on the plus sign to bring up context menu
3. Scroll over the menu popup

**Expected behavior**
*Should be able to hover of the context menu options and select the proper option.*

**Screenshots/Videos**
*https://youtu.be/5VYkRpWBqKM*

**Environment (please complete the following information):**
- OS: Ubuntu 20.04
- Browser Chrome Version 91.0.4472.114 (Official Build) (64-bit)
- Zionbuilder Version 2.6.1

**Additional context**
*If I scroll up the page even by a few pixels, the issue does not happen.
Same thing happens in an Incognito window*

**Comment by zauan** [comment]
This issue was resolved in v2.7.1. Will close for now
