### ISSUE TITLE
Menu in header issue

### ISSUE THREAD

**Issue by jonebennett** [zionbuilder/zionbuilder#559]
When using theme builder my menu is messed up.  looks like this..

using header template included...

![Screen Shot 2021-07-11 at 5 26 50 PM](https://user-images.githubusercontent.com/16633951/125210339-385f1480-e26d-11eb-9ed8-12d6b47a15de.jpg)

please help asap

**Comment by zauan** [comment]
Hi there,

this was resolved in the 2.7.1 update.
