### ISSUE TITLE
Console errors in builder 'Unable to preventDefault inside passive event listener invocation.'

### ISSUE THREAD

**Issue by wplit** [zionbuilder/zionbuilder#567]
**Describe the bug**
Just this error hitting repeatidly in the console when inside the builder.

"editor.js?ver=2.7.0:1 Unable to preventDefault inside passive event listener invocation."

**Steps to reproduce**
Click the button to add a new element.
Scroll down the modal popup to the bottom of the elements.
Try to keep scrolling.
Check the browser console.

**Expected behavior**
No errors in console.

**What actually happens**
Errors in console :)

**Environment (please complete the following information):**
Zionbuilder 2.7.0

**Comment by zauan** [comment]
This was resolved in the upcoming 2.7.2 update
