### ISSUE TITLE
Does not work. Forms in Zion the Builder

### ISSUE THREAD

**Issue by AndreyBrakov** [zionbuilder/zionbuilder#569]
Hello dear comrades! I am a novice web developer from Voronezh. I had problems with the Zion Builder plugin (the main plugin in which the page is constructed.) I can't add and change the form, and their fields. It just doesn't respond to button clicks.I Googled about a similar problem and was advised to clean the cache, update everything. deprecated components, deactivate all plugins and activate them again. And all this did not help. I tried these operations on several computers. And nothing comes out. I tried to create a blank page, and add the same form to it. The result is the same. Everything worked fine last week. What should I do? Thank you in advance I closed the previous question by accident

![Снимок экрана 2021-07-23 в 12 13 42](https://user-images.githubusercontent.com/87857457/126775805-48171ee8-45ae-4e67-9685-6712cda8def8.png)
![Снимок экрана 2021-07-23 в 13 38 32](https://user-images.githubusercontent.com/87857457/126775823-ee35a1b3-66f2-46e2-a08f-261b253ec2e8.png)

**Comment by zauan** [comment]
Hi there,

thank you for contacting us. From the images you have posted, it seems you are using the builder that comes with a Hogash theme. Can you please contact Hogash support at my.hogash.com ?

This repository is for the https://zionbuilder.io builder.

**Comment by AndreyBrakov** [comment]
> Всем привет,
> 
> Благодарим Вас за обращение к нам. Судя по размещенным вами изображениям, похоже, что вы используете конструктор, который поставляется с темой Hogash. Не могли бы вы связаться со службой поддержки Hogash на my.hogash.com?
> 
> Этот репозиторий предназначен для [сборщика https://zionbuilder.io](https://zionbuilder.io) .

thanks.
