### ISSUE TITLE
Problem with the countdown display

### ISSUE THREAD

**Issue by Almaz** [zionbuilder/zionbuilder#577]
The labels under items (days, hours, minutes, seconds) stop displaying when their value is "00" or "01".

**Steps to reproduce**
1. Create a countdown.
2. Go to its properties.
3. Set it so that the elements have the values "00" or "01".
4. Change the labels by entering any values in the "Days text", "Hours text", "Minutes text", "Seconds text" fields.
5. See error.

**Expected behavior**
Labels whose default values have been changed to custom values are not displayed under "00" and "01".

**What actually happens**
Probably, the labels do not have enough width at the corresponding values of the main elements and they are hidden.

**Screencast**
https://youtu.be/bQNfm1jiR-8

**Environment**
- OS: Linux
- Browser Chromium: 92.0.4515.107, (x64)
- Zionbuilder Version: 2.7.0 Pro

**Comment by Almaz** [comment]
It would also be nice if the individual blocks of countdown items were the same width, regardless of the length of the label (hours are shorter than minutes and others, so this block is narrower).

**Comment by zauan** [comment]
Hi there,

This will be resolved in the upcoming 2.7.2 update
