### ISSUE TITLE
Incorrect design of WordPress widget options

### ISSUE THREAD

**Issue by Almaz** [zionbuilder/zionbuilder#578]
The tag cloud options fragment has light colors on the general tab when the dark builder theme is enabled.
*This is relevant to the (all) following elements: Pages, Calendar, Archives, Audio, Image, Gallery, Video, Meta, Search, Text, Categories, Recent Posts, Recent Comments, RSS, Tag Cloud, Navigation Menu, Custom HTML, and even KallyasX - Recent Posts*

**Steps to reproduce**:
1. Go to General Settings > Appearance.
2. Select the dark builder theme.
3. Open the page for editing.
4. Add the Recent Posts (or any other element from the WORDPRESS WIDGETS section).
5. Start editing the element.
6. Go to Options > General.
7. See the bug.

**Screenshot**
https://ok.me/k5gl

**Environment (please complete the following information):**
- OS: Linux
- Browser Chromium: 92.0.4515.107, (x64)
- Zionbuilder Version: 2.7.0 Pro

**Comment by zauan** [comment]
Hi there,

thank you for reporting this. A fix will be available in v2.7.1
