### ISSUE TITLE
Cannot upgrade to PRO with purchase from AppSumo 

### ISSUE THREAD

**Issue by Jakchan** [zionbuilder/zionbuilder#579]
Try to find update issue but nothing match
There is no explain how to upgrade to PRO version when purchase through appSUmo in help section.

**Comment by zauan** [comment]
Hi there,

The PRO version requires both the FREE and PRO plugin installed and activated.

After you have both plugins active, a new menu item will appear in the Zion Builder dashboard as seen in the image:

![image](https://user-images.githubusercontent.com/5928748/127766856-6a86d7aa-f4f0-41f6-bb51-fc2ba0e3ce97.png)

In this field you will have to enter the PRO license key

**Comment by Jakchan** [comment]
This is my screen, it is not like the one u show
![Zion](https://user-images.githubusercontent.com/88178665/127767000-c0508d03-e82d-499a-9525-7fc89fca5f7b.png)
