### ISSUE TITLE
Repeater provider bug

### ISSUE THREAD

**Issue by donzon123** [zionbuilder/zionbuilder#586]
I have 300+ product categories.
Provider properties:
Post type - product
Taxonomy - product categories
Term select - > giving only 20-25 categories. Searching by name not see all categories, dropdown list not all categories.

**Comment by donzon123** [comment]
update - TERM SELECT showing only first 25 entries by alphabet

**Comment by zauan** [comment]
Hi there, thank you for taking the time to open the ticket. My team just finished the test and it seems to be a problem. It will be resolved in the next week update

Best regards,
Stefan

**Comment by zauan** [comment]
This was resolved and it will be available in v2.7.2
