### ISSUE TITLE
My ACFs don't appear in Dynamic data option

### ISSUE THREAD

**Issue by Arrmani** [zionbuilder/zionbuilder#588]
Hello,

I use Zion Builder Pro 2.7.1 and ACF Pro 5.9.9

I use ACF with the products as you can see on this screenshot https://drive.google.com/file/d/1-jUZLaWQEOLfif5kAFc9qyjbfWj1jtpY/view?usp=drivesdk

I can't see my fields in Zion Builder. 

I insert a text bloc > Edit > “Dynamic data” option > From the “Field to display” option, I have to select my field but I see no fields. Please see here: https://drive.google.com/file/d/17Ldh5TKAqS5fvzKM0n1yKA96y42axFHd/view?usp=drivesdk

Do you know how I can resolve this problem ?

Many thanks

**Comment by zauan** [comment]
Hi there,

this was resolved for the 2.7.2 update.
