### ISSUE TITLE
AppSumo Zombuilder pro install error.

### ISSUE THREAD

**Issue by GinoPolo** [zionbuilder/zionbuilder#590]
**Describe the bug**
*After installing ZionBuilder through Wordpress search, I proceed to upload and install the latest ZionBuilder Pro plugin zip file. I then receive a fatal error instead of a successful ZionBuilder Pro activation/install.*

**Have you tried all the steps at https://zionbuilder.io/documentation/having-problems-using-zion-builder/?**
*Yes*

**Steps to reproduce**
1. InstallZionBuilder through Wordpress plugin search
2. Go to 'Add New Plugin'
3. Click on 'Upload File'
4. Select latest ZionBuilder Pro zip file (zion-builder-pro-v2.7.1).
5. Activate Plugin

**Expected behavior**
*ZionBuilder Pro activated*

**What actually happens**
*Fatal error: Cannot use ZionBuilder\Plugin as Plugin because the name is already in use in /home/vertigop/public_html/wp-content/plugins/zionbuilder-pro/includes/Icons.php on line 5
There has been a critical error on this website. Please check your site admin email inbox for instructions.*

**Screenshots/Videos**

![Screen Shot 2021-08-09 at 3 45 53 PM](https://user-images.githubusercontent.com/25613872/128767870-9d83d38b-6ce9-4578-a9eb-bd5c9546a063.png)

**Environment (please complete the following information):**
- OS: macOS Big Sur Version 11.4
- Safari Version 14.1.1
- Zionbuilder Version 2.7.1

**Additional context**
*ZionBuilder Pro licence purchased through AppSumo*

**Comment by zauan** [comment]
Hi there, Sorry to see that you encountered problems. Can you please let me know if you are using the 2.7.1 version for both the free and pro plugin? From the error you've provided, I cannot get much information.

**Comment by GinoPolo** [comment]
Hello @zauan,
Yes I am using version 2.7.1 for both the free and pro plugin. My current WordPress PHP version is 5.6.22.
Thanks.

**Comment by zauan** [comment]
Hi there,

it seems that you are using an outdated version of PHP and this may cause problems. I am now investigating the mentioned problem by using PHP version 5.6.22, however, in the meantime, would it be possible to update your PHP version to at least PHP 7 if not PHP 8?

**Comment by zauan** [comment]
Upon investigation, there seems to be a problem with the PHP 5.6.22 version, and a fix for this will be available in the 2.7.2 version of the builder.
