### ISSUE TITLE
archive page's pagination issue

### ISSUE THREAD

**Issue by orson1129** [zionbuilder/zionbuilder#592]
Hi there,
If I want to create a pagination that automatically apply on current archive page (because I have many archive pages of Taxonomies). what should I do?

**Comment by zauan** [comment]
Hi there,

Can you please give me more details? The builder already has the "Pagination" element that adds the pagination to your page. This must be used inside a repeater provider for it to work.

Also, we are aware of a bug with the pagination element that was resolved and the fix will be available in the next update.

**Comment by zauan** [comment]
Hi there, the fix for this will be available in v2.7.2 that will be released this week
