### ISSUE TITLE
Zion Builder CSS is not working on Frontend

### ISSUE THREAD

**Issue by Mrskt** [zionbuilder/zionbuilder#593]
**Describe the bug**

Hi guys,
In Zion Builder, Everything is working on backend (editing screen) but not working on Frontend (live page).Actually CSS is not working on Frontend.

I am using Neve theme and WP Rocket Plugin on my site.

Please Help…..
**Have you tried all the steps at https://zionbuilder.io/documentation/having-problems-using-zion-builder/?**
Yes

**Steps to reproduce**
1. Go to 'Neve Theme's Custom Layouts'
2. Build a layout with Zion and save it
3. Goto Frontend to view that layout or page.
4. You will see CSS will not showing 

**Expected behavior**
Styles will not load

**What actually happens**
Only raw html is showing, CSS not Loading.

**Screenshots/Videos**
![IMG_20210815_165133_124](https://user-images.githubusercontent.com/81372210/129477340-d3feff33-4277-447d-96c7-405f1097b6b5.jpg)
![IMG_20210815_165135_878](https://user-images.githubusercontent.com/81372210/129477341-6cad410d-1578-4053-bc75-2353308f39a1.jpg)

**Comment by zauan** [comment]
Hi there,

It may be possible that your server cannot generate the files. Can you please check the following location and let me know if you see any files? \wp-content\uploads\zionbuilder\cache

**Comment by Mrskt** [comment]
Hi @zauan ,
After Clearing Cloudflare Cache Everything is Working, But still need Compatibility improvements with Neve Theme.

**Comment by zauan** [comment]
Hi there,

I am glad to see that it is working. regarding Neve theme, can you please open a new ticket and let us know what is not working properly? It may be possible that the Neve theme developers needs to add a compatibility layer with our builder.

Thank you,
Stefan

**Comment by Mrskt** [comment]
Yes, Neve theme needs some improvements.
Recently, i purchased Zion pro plan and my some friends also about to buy. I think Zion Builder needs to add some more pro sections and templates and please keep the plugin regularly updated and add compatibility with other plugins like Rank Math, Yoast, etc.

Thank you
