### ISSUE TITLE
Zion Builder 2.7.1 unable to create an empty canvas

### ISSUE THREAD

**Issue by irboi746** [zionbuilder/zionbuilder#595]
**Describe the bug**
I am using Zion Builder 2.7.1 and I am trying to use the theme builder to create the header and footer of the template. However, I am unable to clear the canvas which is used by the original theme (Wordpress default theme with nothing on top) with the "page option" --> "blank canvas" option . 

**Have you tried all the steps at https://zionbuilder.io/documentation/having-problems-using-zion-builder/?**
*Yes*

**Steps to reproduce**
From the edit header option in Zion Theme Builder tab
1. Go to 'page options'
2. Click on 'blank canvas'
3. but the custom wordpress page is still seen and there is no change to it.

**Expected behavior**
Blank Canvas to create webpage should be seen

**What actually happens**
Nothing happened. That is the problem.

**Screenshots/Videos**
*If applicable, add screenshots/videos to help explain the problem.*
![image](https://user-images.githubusercontent.com/88809233/129816468-91073c92-f5e7-4ce8-826b-c209fa686684.png)

**Environment (please complete the following information):**
- Zionbuilder Version 2.7.1

**Additional context**
Nil

**Comment by zauan** [comment]
Hi there,

i cannot reproduce this locally. The plugin should set the blank canvas automatically for all theme builder templates.

From your image, I notices that you get a 404 error. Can you please clear WordPress permalinks and try to see it this resolves your problem?

**Comment by irboi746** [comment]
Hi, It solves the issue!
Thanks alot!
