### ISSUE TITLE
Footer template is hovering

### ISSUE THREAD

**Issue by irboi746** [zionbuilder/zionbuilder#597]
**Describe the bug**
Footer template its not exactly at the bottom. It appears to hover and it will only truly be at the bottom when the content stretches the right length.

**Have you tried all the steps at https://zionbuilder.io/documentation/having-problems-using-zion-builder/?**
*Yes*

**Steps to reproduce**
1. Creating template from zion template builder
2. I created Header and footer template and assigned them accordingly
3. See error

**Expected behavior**
Footer at the bottom of the page without content in the body

**What actually happens**
Footer hovering.

**Screenshots/Videos**
![image](https://user-images.githubusercontent.com/88809233/129885441-44344f7c-75d2-4f32-b681-95a765cdafe7.png)

**Environment (please complete the following information):**
- Zionbuilder Version 2.7.1

**Additional context**
nil

**Comment by zauan** [comment]
Hi there,

This is somehow expected. The theme sets a 100% height to the page and the content is too small to push the footer to the bottom.
