### ISSUE TITLE
Visual Bug: When Custom Font options enlarged, wpadminbar overlaps buttons

### ISSUE THREAD

**Issue by rorar** [zionbuilder/zionbuilder#647]
**Describe the bug**
If you click on the enlarge button on a 1920x1080 screen, the minimize button and close button is half hidden:
![image](https://user-images.githubusercontent.com/44790144/143679225-5f8a4edb-b94c-4550-aca3-0410534f3ea2.png)

*Write a explanatory description of the bug.*
UI Bug

**Have you tried all the steps at https://zionbuilder.io/documentation/having-problems-using-zion-builder/?**
Yes

**Steps to reproduce**
1. Go to 
/wp-admin/admin.php?page=zionbuilder#/settings/font-options/custom-fonts
2. Click on 
![image](https://user-images.githubusercontent.com/44790144/143679605-b1b1e916-9263-4bee-b6ee-f9a629c11908.png)
3. Click on
![image](https://user-images.githubusercontent.com/44790144/143679629-429077c2-9605-4904-aa2e-33c98174f524.png)

**Expected behavior**
"Pop-up" should be ~90% vh and buttons should not be overlapped

*What should have happend after following the steps above.*
see expected behavior

**What actually happens**
see Describe the Bug

*Provide a concise message of what is actually happening.*
see above

**Screenshots/Videos**
attached above
*If applicable, add screenshots/videos to help explain the problem.*
attached above

**Environment (please complete the following information):**
- OS: Windows 11 
- Browser chrome version 96.0.4664.45 (officual build) (64-Bit)
- Zionbuilder Version 5.8.2 PRO

**Additional context**
*Add any other context about the problem here.*

**Comment by zauan** [comment]
This was resolved for v3.0.0
