### ISSUE TITLE
Custom Font: WOFF2 Support

### ISSUE THREAD

**Issue by rorar** [zionbuilder/zionbuilder#648]
**Describe the bug**
*Write a explanatory description of the bug.*
The documentation stated that Zion Builder got WOFF2 support
![image](https://user-images.githubusercontent.com/44790144/143680112-50fe083d-9730-48b2-90be-d7550aa379fa.png)
https://zionbuilder.io/documentation/custom-fonts/

**Have you tried all the steps at https://zionbuilder.io/documentation/having-problems-using-zion-builder/?**
Yes

**Steps to reproduce**
1. Go to 
/wp-admin/admin.php?page=zionbuilder#/settings/font-options/custom-fonts
2. Click on 
![image](https://user-images.githubusercontent.com/44790144/143680163-83e0b1c0-fd73-45d6-9fec-def467d7d127.png)
3. Scroll down to
* file section
4. See error - No WOFF2 Upload option
![image](https://user-images.githubusercontent.com/44790144/143680225-0434eb48-aa62-4a8a-b069-44ca6d225282.png)

**Expected behavior**
*What should have happend after following the steps above.*
See option to upload WOFF2

**What actually happens**
*Provide a concise message of what is actually happening.*
No option to upload WOFF2

**Screenshots/Videos**
*If applicable, add screenshots/videos to help explain the problem.*
see above

**Environment (please complete the following information):**
- OS: Windows 11
- Browser 96.0.4664.45 (official build) (64-Bit)
- Zionbuilder Version 5.8.2 Pro

**Additional context**
*Add any other context about the problem here.*

**Comment by zauan** [comment]
Hi there,

It seems that the documentation was wrong. Woff2 support was added in v3.0 version that is not yet released
