### ISSUE TITLE
Zion Builder Kallyas Theme

### ISSUE THREAD

**Issue by BegVK** [zionbuilder/zionbuilder#78]
Hi Guys,

i have installed the new Zion Builder and tried to work with it.. but when trying to edit an page or create a new one with new zion builder.. the screen will load the whole day with no response...

_
<img width="853" alt="Bildschirmfoto 2020-07-23 um 22 50 50" src="https://user-images.githubusercontent.com/66945908/88337637-50294a00-cd37-11ea-8a96-55f09059e8c5.png">

**Comment by zauan** [comment]
Hi there,

Thank you for taking the time to open this ticket. At the moment, the new ZionBuilder is not compatible with Kallyas. A fix for this will be available early next week. Please note however that a new Kallyas update that will include the Zion Builder plugin is worked on.

Best regards,
Stefan

**Comment by BegVK** [comment]
Hi stefan!

Thank you so much for this related answer!

KR

Dzenis

Von: Balasa Sorin Stefan <notifications@github.com>
Antworten an: zionbuilder/zionbuilder <reply@reply.github.com>
Datum: Freitag, 24. Juli 2020 um 12:29
An: zionbuilder/zionbuilder <zionbuilder@noreply.github.com>
Cc: BegVK <dzenis.rizvic@outlook.de>, Author <author@noreply.github.com>
Betreff: Re: [zionbuilder/zionbuilder] Zion Builder Kallyas Theme (#78)


Hi there,

Thank you for taking the time to open this ticket. At the moment, the new ZionBuilder is not compatible with Kallyas. A fix for this will be available early next week. Please note however that a new Kallyas update that will include the Zion Builder plugin is worked on.

Best regards,
Stefan

**Comment by zauan** [comment]
If you want to check out what the Zion Builder plugin can do, you can install it on a WordPress default theme.

I will keep this ticket open until the update is available containing the Kallyas fix.

Best regards,
Stefan

**Comment by BegVK** [comment]
Yeah thats great!

So you mean an Wordpress default theme like Twenty etc..?

KR

Von: Balasa Sorin Stefan <notifications@github.com>
Antworten an: zionbuilder/zionbuilder <reply@reply.github.com>
Datum: Freitag, 24. Juli 2020 um 12:49
An: zionbuilder/zionbuilder <zionbuilder@noreply.github.com>
Cc: BegVK <dzenis.rizvic@outlook.de>, Author <author@noreply.github.com>
Betreff: Re: [zionbuilder/zionbuilder] Zion Builder Kallyas Theme (#78)


If you want to check out what the Zion Builder plugin can do, you can install it on a WordPress default theme.

I will keep this ticket open until the update is available containing the Kallyas fix.

Best regards,
Stefan

**Comment by zauan** [comment]
Yes!

**Comment by zauan** [comment]
This has been resolved in the latest Zion Builder version ( v1.0.1 )
